INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Abreulândia', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Aguiarnópolis', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Aliança do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Almas', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Alvorada', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Ananás', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Angico', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Aparecida do Rio Negro', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Aragominas', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Araguacema', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Araguaçu', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Araguaína', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Araguanã', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Araguatins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Arapoema', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Arraias', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Augustinópolis', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Aurora do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Axixá do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Babaçulândia', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Bandeirantes do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Barra do Ouro', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Barrolândia', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Bernardo Sayão', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Bom Jesus do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Brasilândia do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Brejinho de Nazaré', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Buriti do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Cachoeirinha', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Campos Lindos', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Cariri do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Carmolândia', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Carrasco Bonito', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Caseara', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Centenário', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Chapada da Natividade', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Chapada de Areia', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Colinas do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Colméia', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Combinado', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Conceição do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Couto de Magalhães', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Cristalândia', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Crixás do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Darcinópolis', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Dianópolis', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Divinópolis do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Dois Irmãos do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Dueré', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Esperantina', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Fátima', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Figueirópolis', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Filadélfia', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Formoso do Araguaia', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Fortaleza do Tabocão', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Goianorte', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Goiatins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Guaraí', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Gurupi', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Ipueiras', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Itacajá', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Itaguatins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Itapiratins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Itaporã do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Jaú do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Juarina', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Lagoa da Confusão', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Lagoa do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Lajeado', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Lavandeira', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Lizarda', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Luzinópolis', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Marianópolis do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Mateiros', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Maurilândia do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Miracema do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Miranorte', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Monte do Carmo', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Monte Santo do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Muricilândia', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Natividade', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Nazaré', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Nova Olinda', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Nova Rosalândia', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Novo Acordo', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Novo Alegre', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Novo Jardim', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Oliveira de Fátima', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Palmas', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Palmeirante', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Palmeiras do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Palmeirópolis', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Paraíso do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Paranã', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Pau D''Arco', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Pedro Afonso', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Peixe', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Pequizeiro', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Pindorama do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Piraquê', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Pium', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Ponte Alta do Bom Jesus', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Ponte Alta do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Porto Alegre do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Porto Nacional', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Praia Norte', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Presidente Kennedy', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Pugmil', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Recursolândia', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Riachinho', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Rio da Conceição', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Rio dos Bois', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Rio Sono', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Sampaio', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Sandolândia', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Santa Fé do Araguaia', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Santa Maria do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Santa Rita do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Santa Rosa do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Santa Tereza do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Santa Terezinha do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('São Bento do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('São Félix do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('São Miguel do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('São Salvador do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('São Sebastião do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('São Valério da Natividade', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Silvanópolis', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Sítio Novo do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Sucupira', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Taguatinga', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Taipas do Tocantins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Talismã', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Tocantínia', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Tocantinópolis', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Tupirama', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Tupiratins', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Wanderlândia', 27);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Xambioá', 27);
