INSERT INTO cidade (nome_cidade, cidade_estado)
VALUES
    ('Afonso Cláudio', 8),
    ('Águia Branca', 8),
    ('Alegre', 8),
    ('Alfredo Chaves', 8),
    ('Alto Rio Novo', 8),
    ('Anchieta', 8),
    ('Apiacá', 8),
    ('Aracruz', 8),
    ('Atilio Vivacqua', 8),
    ('Baixo Guandu', 8),
    ('Barra de São Francisco', 8),
    ('Boa Esperança', 8),
    ('Bom Jesus do Norte', 8),
    ('Brejetuba', 8),
    ('Cachoeiro de Itapemirim', 8),
    ('Cariacica', 8),
    ('Castelo', 8),
    ('Colatina', 8),
    ('Conceição da Barra', 8),
    ('Conceição do Castelo', 8),
    ('Divino de São Lourenço', 8),
    ('Domingos Martins', 8),
    ('Dores do Rio Preto', 8),
    ('Ecoporanga', 8),
    ('Fundão', 8),
    ('Governador Lindenberg', 8),
    ('Guaçuí', 8),
    ('Guarapari', 8),
    ('Ibatiba', 8),
    ('Ibiraçu', 8),
    ('Ibitirama', 8),
    ('Iconha', 8),
    ('Irupi', 8),
    ('Itaguaçu', 8),
    ('Itapemirim', 8),
    ('Itarana', 8),
    ('Iúna', 8),
    ('Jaguaré', 8),
    ('Jerônimo Monteiro', 8),
    ('João Neiva', 8),
    ('Laranja da Terra', 8),
    ('Linhares', 8),
    ('Mantenópolis', 8),
    ('Marataízes', 8),
    ('Marechal Floriano', 8),
    ('Marilândia', 8),
    ('Mimoso do Sul', 8),
    ('Montanha', 8),
    ('Mucurici', 8),
    ('Muniz Freire', 8),
    ('Muqui', 8),
    ('Nova Venécia', 8),
    ('Pancas', 8),
    ('Pedro Canário', 8),
    ('Pinheiros', 8),
    ('Piúma', 8),
    ('Ponto Belo', 8),
    ('Presidente Kennedy', 8),
    ('Rio Bananal', 8),
    ('Rio Novo do Sul', 8),
    ('Santa Leopoldina', 8),
    ('Santa Maria de Jetibá', 8),
    ('Santa Teresa', 8),
    ('São Domingos do Norte', 8),
    ('São Gabriel da Palha', 8),
    ('São José do Calçado', 8),
    ('São Mateus', 8),
    ('São Roque do Canaã', 8),
    ('Serra', 8),
    ('Sooretama', 8),
    ('Vargem Alta', 8),
    ('Venda Nova do Imigrante', 8),
    ('Viana', 8),
    ('Vila Pavão', 8),
    ('Vila Valério', 8),
    ('Vila Velha', 8),
    ('Vitória', 8);
