INSERT INTO cidade (nome_cidade, cidade_estado) VALUES
('Alvarães', 4),
('Amaturá', 4),
('Anamã', 4),
('Anori', 4),
('Apuí', 4),
('Atalaia do Norte', 4),
('Autazes', 4),
('Barcelos', 4),
('Barreirinha', 4),
('Benjamin Constant', 4),
('Beruri', 4),
('Boa Vista do Ramos', 4),
('Boca do Acre', 4),
('Borba', 4),
('Caapiranga', 4),
('Canutama', 4),
('Carauari', 4),
('Careiro', 4),
('Careiro da Várzea', 4),
('Coari', 4),
('Codajás', 4),
('Eirunepé', 4),
('Envira', 4),
('Fonte Boa', 4),
('Guajará', 4),
('Humaitá', 4),
('Ipixuna', 4),
('Iranduba', 4),
('Itacoatiara', 4),
('Itamarati', 4),
('Itapiranga', 4),
('Japurá', 4),
('Juruá', 4),
('Jutaí', 4),
('Lábrea', 4),
('Manacapuru', 4),
('Manaquiri', 4),
('Manaus', 4),
('Manicoré', 4),
('Maraã', 4),
('Maués', 4),
('Nhamundá', 4),
('Nova Olinda do Norte', 4),
('Novo Airão', 4),
('Novo Aripuanã', 4),
('Parintins', 4),
('Pauini', 4),
('Presidente Figueiredo', 4),
('Rio Preto da Eva', 4),
('Santa Isabel do Rio Negro', 4),
('Santo Antônio do Içá', 4),
('São Gabriel da Cachoeira', 4),
('São Paulo de Olivença', 4),
('São Sebastião do Uatumã', 4),
('Silves', 4),
('Tabatinga', 4),
('Tapauá', 4),
('Tefé', 4),
('Tonantins', 4),
('Uarini', 4),
('Urucará', 4),
('Urucurituba', 4);
