INSERT INTO cidade (nome_cidade, cidade_estado) VALUES
                                                    ('Aceguá', 21),
                                                    ('Água Santa', 21),
                                                    ('Agudo', 21),
                                                    ('Ajuricaba', 21),
                                                    ('Alecrim', 21),
                                                    ('Alegrete', 21),
                                                    ('Alegria', 21),
                                                    ('Almirante Tamandaré do Sul', 21),
                                                    ('Alpestre', 21),
                                                    ('Alto Alegre', 21),
                                                    ('Alto Feliz', 21),
                                                    ('Alvorada', 21),
                                                    ('Amaral Ferrador', 21),
                                                    ('Ametista do Sul', 21),
                                                    ('André da Rocha', 21),
                                                    ('Anta Gorda', 21),
                                                    ('Antônio Prado', 21),
                                                    ('Arambaré', 21),
                                                    ('Araricá', 21),
                                                    ('Aratiba', 21),
                                                    ('Arroio do Meio', 21),
                                                    ('Arroio do Padre', 21),
                                                    ('Arroio do Sal', 21),
                                                    ('Arroio do Tigre', 21),
                                                    ('Arroio dos Ratos', 21),
                                                    ('Arroio Grande', 21),
                                                    ('Arvorezinha', 21),
                                                    ('Augusto Pestana', 21),
                                                    ('Áurea', 21),
                                                    ('Bagé', 21),
                                                    ('Balneário Pinhal', 21),
                                                    ('Barão', 21),
                                                    ('Barão de Cotegipe', 21),
                                                    ('Barão do Triunfo', 21),
                                                    ('Barra do Guarita', 21),
                                                    ('Barra do Quaraí', 21),
                                                    ('Barra do Ribeiro', 21),
                                                    ('Barra do Rio Azul', 21),
                                                    ('Barra Funda', 21),
                                                    ('Barracão', 21),
                                                    ('Barros Cassal', 21),
                                                    ('Benjamin Constant do Sul', 21),
                                                    ('Bento Gonçalves', 21),
                                                    ('Boa Vista das Missões', 21),
                                                    ('Boa Vista do Buricá', 21),
                                                    ('Boa Vista do Cadeado', 21),
                                                    ('Boa Vista do Incra', 21),
                                                    ('Boa Vista do Sul', 21),
                                                    ('Bom Jesus', 21),
                                                    ('Bom Princípio', 21),
                                                    ('Bom Progresso', 21),
                                                    ('Bom Retiro do Sul', 21),
                                                    ('Boqueirão do Leão', 21),
                                                    ('Bossoroca', 21),
                                                    ('Bozano', 21),
                                                    ('Braga', 21),
                                                    ('Brochier', 21),
                                                    ('Butiá', 21),
                                                    ('Caçapava do Sul', 21),
                                                    ('Cacequi', 21),
                                                    ('Cachoeira do Sul', 21),
                                                    ('Cachoeirinha', 21),
                                                    ('Cacique Doble', 21),
                                                    ('Caibaté', 21),
                                                    ('Caiçara', 21),
                                                    ('Camaquã', 21),
                                                    ('Camargo', 21),
                                                    ('Cambará do Sul', 21),
                                                    ('Campestre da Serra', 21),
                                                    ('Campina das Missões', 21),
                                                    ('Campinas do Sul', 21),
                                                    ('Campo Bom', 21),
                                                    ('Campo Novo', 21),
                                                    ('Campos Borges', 21),
                                                    ('Candelária', 21),
                                                    ('Cândido Godói', 21),
                                                    ('Candiota', 21),
                                                    ('Canela', 21),
                                                    ('Canguçu', 21),
                                                    ('Canoas', 21),
                                                    ('Canudos do Vale', 21),
                                                    ('Capão Bonito do Sul', 21),
                                                    ('Capão da Canoa', 21),
                                                    ('Capão do Cipó', 21),
                                                    ('Capão do Leão', 21),
                                                    ('Capela de Santana', 21),
                                                    ('Capitão', 21),
                                                    ('Capivari do Sul', 21),
                                                    ('Caraá', 21),
                                                    ('Carazinho', 21),
                                                    ('Carlos Barbosa', 21),
                                                    ('Carlos Gomes', 21),
                                                    ('Casca', 21),
                                                    ('Caseiros', 21),
                                                    ('Catuípe', 21),
                                                    ('Caxias do Sul', 21),
                                                    ('Centenário', 21),
                                                    ('Cerrito', 21),
                                                    ('Cerro Branco', 21),
                                                    ('Cerro Grande', 21),
                                                    ('Cerro Grande do Sul', 21),
                                                    ('Cerro Largo', 21),
                                                    ('Chapada', 21),
                                                    ('Charqueadas', 21),
                                                    ('Charrua', 21),
                                                    ('Chiapetta', 21),
                                                    ('Chuí', 21),
                                                    ('Chuvisca', 21),
                                                    ('Cidreira', 21),
                                                    ('Ciríaco', 21),
                                                    ('Colinas', 21),
                                                    ('Colorado', 21),
                                                    ('Condor', 21),
                                                    ('Constantina', 21),
                                                    ('Coqueiro Baixo', 21),
                                                    ('Coqueiros do Sul', 21),
                                                    ('Coronel Barros', 21),
                                                    ('Coronel Bicaco', 21),
                                                    ('Coronel Pilar', 21),
                                                    ('Cotiporã', 21),
                                                    ('Coxilha', 21),
                                                    ('Crissiumal', 21),
                                                    ('Cristal', 21),
                                                    ('Cristal do Sul', 21),
                                                    ('Cruz Alta', 21),
                                                    ('Cruzaltense', 21),
                                                    ('Cruzeiro do Sul', 21),
                                                    ('David Canabarro', 21),
                                                    ('Derrubadas', 21),
                                                    ('Dezesseis de Novembro', 21),
                                                    ('Dilermando de Aguiar', 21),
                                                    ('Dois Irmãos', 21),
                                                    ('Dois Irmãos das Missões', 21),
                                                    ('Dois Lajeados', 21),
                                                    ('Dom Feliciano', 21),
                                                    ('Dom Pedrito', 21),
                                                    ('Dom Pedro de Alcântara', 21),
                                                    ('Dona Francisca', 21),
                                                    ('Doutor Maurício Cardoso', 21),
                                                    ('Doutor Ricardo', 21),
                                                    ('Eldorado do Sul', 21),
                                                    ('Encantado', 21),
                                                    ('Encruzilhada do Sul', 21),
                                                    ('Engenho Velho', 21),
                                                    ('Entre Rios do Sul', 21),
                                                    ('Entre-Ijuís', 21),
                                                    ('Erebango', 21),
                                                    ('Erechim', 21),
                                                    ('Ernestina', 21),
                                                    ('Erval Grande', 21),
                                                    ('Erval Seco', 21),
                                                    ('Esmeralda', 21),
                                                    ('Esperança do Sul', 21),
                                                    ('Espumoso', 21),
                                                    ('Estação', 21),
                                                    ('Estância Velha', 21),
                                                    ('Esteio', 21),
                                                    ('Estrela', 21),
                                                    ('Estrela Velha', 21),
                                                    ('Eugênio de Castro', 21),
                                                    ('Fagundes Varela', 21),
                                                    ('Farroupilha', 21),
                                                    ('Faxinal do Soturno', 21),
                                                    ('Faxinalzinho', 21),
                                                    ('Fazenda Vilanova', 21),
                                                    ('Feliz', 21),
                                                    ('Flores da Cunha', 21),
                                                    ('Floriano Peixoto', 21),
                                                    ('Fontoura Xavier', 21),
                                                    ('Formigueiro', 21),
                                                    ('Forquetinha', 21),
                                                    ('Fortaleza dos Valos', 21),
                                                    ('Frederico Westphalen', 21),
                                                    ('Garibaldi', 21),
                                                    ('Garruchos', 21),
                                                    ('Gaurama', 21),
                                                    ('General Câmara', 21),
                                                    ('Gentil', 21),
                                                    ('Getúlio Vargas', 21),
                                                    ('Giruá', 21),
                                                    ('Glorinha', 21),
                                                    ('Gramado', 21),
                                                    ('Gramado dos Loureiros', 21),
                                                    ('Gramado Xavier', 21),
                                                    ('Gravataí', 21),
                                                    ('Guabiju', 21),
                                                    ('Guaíba', 21),
                                                    ('Guaporé', 21),
                                                    ('Guarani das Missões', 21),
                                                    ('Harmonia', 21),
                                                    ('Herval', 21),
                                                    ('Herveiras', 21),
                                                    ('Horizontina', 21),
                                                    ('Hulha Negra', 21),
                                                    ('Humaitá', 21),
                                                    ('Ibarama', 21),
                                                    ('Ibiaçá', 21),
                                                    ('Ibiraiaras', 21),
                                                    ('Ibirapuitã', 21),
                                                    ('Ibirubá', 21),
                                                    ('Igrejinha', 21),
                                                    ('Ijuí', 21),
                                                    ('Ilópolis', 21),
                                                    ('Imbé', 21),
                                                    ('Imigrante', 21),
                                                    ('Independência', 21),
                                                    ('Inhacorá', 21),
                                                    ('Ipê', 21),
                                                    ('Ipiranga do Sul', 21),
                                                    ('Iraí', 21),
                                                    ('Itaara', 21),
                                                    ('Itacurubi', 21),
                                                    ('Itapuca', 21),
                                                    ('Itaqui', 21),
                                                    ('Itati', 21),
                                                    ('Itatiba do Sul', 21),
                                                    ('Ivorá', 21),
                                                    ('Ivoti', 21),
                                                    ('Jaboticaba', 21),
                                                    ('Jacuizinho', 21),
                                                    ('Jacutinga', 21),
                                                    ('Jaguarão', 21),
                                                    ('Jaguari', 21),
                                                    ('Jaquirana', 21),
                                                    ('Jari', 21),
                                                    ('Jóia', 21),
                                                    ('Júlio de Castilhos', 21),
                                                    ('Lagoa Bonita do Sul', 21),
                                                    ('Lagoa dos Três Cantos', 21),
                                                    ('Lagoa Vermelha', 21),
                                                    ('Lagoão', 21),
                                                    ('Lajeado', 21),
                                                    ('Lajeado do Bugre', 21),
                                                    ('Lavras do Sul', 21),
                                                    ('Liberato Salzano', 21),
                                                    ('Lindolfo Collor', 21),
                                                    ('Linha Nova', 21),
                                                    ('Maçambara', 21),
                                                    ('Machadinho', 21),
                                                    ('Mampituba', 21),
                                                    ('Manoel Viana', 21),
                                                    ('Maquiné', 21),
                                                    ('Maratá', 21),
                                                    ('Marau', 21),
                                                    ('Marcelino Ramos', 21),
                                                    ('Mariana Pimentel', 21),
                                                    ('Mariano Moro', 21),
                                                    ('Marques de Souza', 21),
                                                    ('Mata', 21),
                                                    ('Mato Castelhano', 21),
                                                    ('Mato Leitão', 21),
                                                    ('Mato Queimado', 21),
                                                    ('Maximiliano de Almeida', 21),
                                                    ('Minas do Leão', 21),
                                                    ('Miraguaí', 21),
                                                    ('Montauri', 21),
                                                    ('Monte Alegre dos Campos', 21),
                                                    ('Monte Belo do Sul', 21),
                                                    ('Montenegro', 21),
                                                    ('Mormaço', 21),
                                                    ('Morrinhos do Sul', 21),
                                                    ('Morro Redondo', 21),
                                                    ('Morro Reuter', 21),
                                                    ('Mostardas', 21),
                                                    ('Muçum', 21),
                                                    ('Muitos Capões', 21),
                                                    ('Muliterno', 21),
                                                    ('Não-Me-Toque', 21),
                                                    ('Nicolau Vergueiro', 21),
                                                    ('Nonoai', 21),
                                                    ('Nova Alvorada', 21),
                                                    ('Nova Araçá', 21),
                                                    ('Nova Bassano', 21),
                                                    ('Nova Boa Vista', 21),
                                                    ('Nova Bréscia', 21),
                                                    ('Nova Candelária', 21),
                                                    ('Nova Esperança do Sul', 21),
                                                    ('Nova Hartz', 21),
                                                    ('Nova Pádua', 21),
                                                    ('Nova Palma', 21),
                                                    ('Nova Petrópolis', 21),
                                                    ('Nova Prata', 21),
                                                    ('Nova Ramada', 21),
                                                    ('Nova Roma do Sul', 21),
                                                    ('Nova Santa Rita', 21),
                                                    ('Novo Barreiro', 21),
                                                    ('Novo Cabrais', 21),
                                                    ('Novo Hamburgo', 21),
                                                    ('Novo Machado', 21),
                                                    ('Novo Tiradentes', 21),
                                                    ('Novo Xingu', 21),
                                                    ('Osório', 21),
                                                    ('Paim Filho', 21),
                                                    ('Palmares do Sul', 21),
                                                    ('Palmeira das Missões', 21),
                                                    ('Palmitinho', 21),
                                                    ('Panambi', 21),
                                                    ('Pantano Grande', 21),
                                                    ('Paraí', 21),
                                                    ('Paraíso do Sul', 21),
                                                    ('Pareci Novo', 21),
                                                    ('Parobé', 21),
                                                    ('Passa Sete', 21),
                                                    ('Passo do Sobrado', 21),
                                                    ('Passo Fundo', 21),
                                                    ('Paulo Bento', 21),
                                                    ('Paverama', 21),
                                                    ('Pedras Altas', 21),
                                                    ('Pedro Osório', 21),
                                                    ('Pejuçara', 21),
                                                    ('Pelotas', 21),
                                                    ('Picada Café', 21),
                                                    ('Pinhal', 21),
                                                    ('Pinhal da Serra', 21),
                                                    ('Pinhal Grande', 21),
                                                    ('Pinheirinho do Vale', 21),
                                                    ('Pinheiro Machado', 21),
                                                    ('Pirapó', 21),
                                                    ('Piratini', 21),
                                                    ('Planalto', 21),
                                                    ('Poço das Antas', 21),
                                                    ('Pontão', 21),
                                                    ('Ponte Preta', 21),
                                                    ('Portão', 21),
                                                    ('Porto Alegre', 21),
                                                    ('Porto Lucena', 21),
                                                    ('Porto Mauá', 21),
                                                    ('Porto Vera Cruz', 21),
                                                    ('Porto Xavier', 21),
                                                    ('Pouso Novo', 21),
                                                    ('Presidente Lucena', 21),
                                                    ('Progresso', 21),
                                                    ('Protásio Alves', 21),
                                                    ('Putinga', 21),
                                                    ('Quaraí', 21),
                                                    ('Quatro Irmãos', 21),
                                                    ('Quevedos', 21),
                                                    ('Quinze de Novembro', 21),
                                                    ('Redentora', 21),
                                                    ('Relvado', 21),
                                                    ('Restinga Seca', 21),
                                                    ('Rio dos Índios', 21),
                                                    ('Rio Grande', 21),
                                                    ('Rio Pardo', 21),
                                                    ('Riozinho', 21),
                                                    ('Roca Sales', 21),
                                                    ('Rodeio Bonito', 21),
                                                    ('Rolador', 21),
                                                    ('Rolante', 21),
                                                    ('Ronda Alta', 21),
                                                    ('Rondinha', 21),
                                                    ('Roque Gonzales', 21),
                                                    ('Rosário do Sul', 21),
                                                    ('Sagrada Família', 21),
                                                    ('Saldanha Marinho', 21),
                                                    ('Salto do Jacuí', 21),
                                                    ('Salvador das Missões', 21),
                                                    ('Salvador do Sul', 21),
                                                    ('Sananduva', 21),
                                                    ('Santa Bárbara do Sul', 21),
                                                    ('Santa Cecília do Sul', 21),
                                                    ('Santa Clara do Sul', 21),
                                                    ('Santa Cruz do Sul', 21),
                                                    ('Santa Margarida do Sul', 21),
                                                    ('Santa Maria', 21),
                                                    ('Santa Maria do Herval', 21),
                                                    ('Santa Rosa', 21),
                                                    ('Santa Tereza', 21),
                                                    ('Santa Vitória do Palmar', 21),
                                                    ('Santana da Boa Vista', 21),
                                                    ('Sant''Ana do Livramento', 21),
                                                    ('Santiago', 21),
                                                    ('Santo Ângelo', 21),
                                                    ('Santo Antônio da Patrulha', 21),
                                                    ('Santo Antônio das Missões', 21),
                                                    ('Santo Antônio do Palma', 21),
                                                    ('Santo Antônio do Planalto', 21),
                                                    ('Santo Augusto', 21),
                                                    ('Santo Cristo', 21),
                                                    ('Santo Expedito do Sul', 21),
                                                    ('São Borja', 21),
                                                    ('São Domingos do Sul', 21),
                                                    ('São Francisco de Assis', 21),
                                                    ('São Francisco de Paula', 21),
                                                    ('São Gabriel', 21),
                                                    ('São Jerônimo', 21),
                                                    ('São João da Urtiga', 21),
                                                    ('São João do Polêsine', 21),
                                                    ('São Jorge', 21),
                                                    ('São José das Missões', 21),
                                                    ('São José do Herval', 21),
                                                    ('São José do Hortêncio', 21),
                                                    ('São José do Inhacorá', 21),
                                                    ('São José do Norte', 21),
                                                    ('São José do Ouro', 21),
                                                    ('São José do Sul', 21),
                                                    ('São José dos Ausentes', 21),
                                                    ('São Leopoldo', 21),
                                                    ('São Lourenço do Sul', 21),
                                                    ('São Luiz Gonzaga', 21),
                                                    ('São Marcos', 21),
                                                    ('São Martinho', 21),
                                                    ('São Martinho da Serra', 21),
                                                    ('São Miguel das Missões', 21),
                                                    ('São Nicolau', 21),
                                                    ('São Paulo das Missões', 21),
                                                    ('São Pedro da Serra', 21),
                                                    ('São Pedro das Missões', 21),
                                                    ('São Pedro do Butiá', 21),
                                                    ('São Pedro do Sul', 21),
                                                    ('São Sebastião do Caí', 21),
                                                    ('São Sepé', 21),
                                                    ('São Valentim', 21),
                                                    ('São Valentim do Sul', 21),
                                                    ('São Valério do Sul', 21),
                                                    ('São Vendelino', 21),
                                                    ('São Vicente do Sul', 21),
                                                    ('Sapiranga', 21),
                                                    ('Sapucaia do Sul', 21),
                                                    ('Sarandi', 21),
                                                    ('Seberi', 21),
                                                    ('Sede Nova', 21),
                                                    ('Segredo', 21),
                                                    ('Selbach', 21),
                                                    ('Senador Salgado Filho', 21),
                                                    ('Sentinela do Sul', 21),
                                                    ('Serafina Corrêa', 21),
                                                    ('Sério', 21),
                                                    ('Sertão', 21),
                                                    ('Sertão Santana', 21),
                                                    ('Sete de Setembro', 21),
                                                    ('Severiano de Almeida', 21),
                                                    ('Silveira Martins', 21),
                                                    ('Sinimbu', 21),
                                                    ('Sobradinho', 21),
                                                    ('Soledade', 21),
                                                    ('Tabaí', 21),
                                                    ('Tapejara', 21),
                                                    ('Tapera', 21),
                                                    ('Tapes', 21),
                                                    ('Taquara', 21),
                                                    ('Taquari', 21),
                                                    ('Taquaruçu do Sul', 21),
                                                    ('Tavares', 21),
                                                    ('Tenente Portela', 21),
                                                    ('Terra de Areia', 21),
                                                    ('Teutônia', 21),
                                                    ('Tio Hugo', 21),
                                                    ('Tiradentes do Sul', 21),
                                                    ('Toropi', 21),
                                                    ('Torres', 21),
                                                    ('Tramandaí', 21),
                                                    ('Travesseiro', 21),
                                                    ('Três Arroios', 21),
                                                    ('Três Cachoeiras', 21),
                                                    ('Três Coroas', 21),
                                                    ('Três de Maio', 21),
                                                    ('Três Forquilhas', 21),
                                                    ('Três Palmeiras', 21),
                                                    ('Três Passos', 21),
                                                    ('Trindade do Sul', 21),
                                                    ('Triunfo', 21),
                                                    ('Tucunduva', 21),
                                                    ('Tunas', 21),
                                                    ('Tupanci do Sul', 21),
                                                    ('Tupanciretã', 21),
                                                    ('Tupandi', 21),
                                                    ('Tuparendi', 21),
                                                    ('Turuçu', 21),
                                                    ('Ubiretama', 21),
                                                    ('União da Serra', 21),
                                                    ('Unistalda', 21),
                                                    ('Uruguaiana', 21),
                                                    ('Vacaria', 21),
                                                    ('Vale do Sol', 21),
                                                    ('Vale Real', 21),
                                                    ('Vale Verde', 21),
                                                    ('Vanini', 21),
                                                    ('Venâncio Aires', 21),
                                                    ('Vera Cruz', 21),
                                                    ('Veranópolis', 21),
                                                    ('Vespasiano Corrêa', 21),
                                                    ('Viadutos', 21),
                                                    ('Viamão', 21),
                                                    ('Vicente Dutra', 21),
                                                    ('Victor Graeff', 21),
                                                    ('Vila Flores', 21),
                                                    ('Vila Lângaro', 21),
                                                    ('Vila Maria', 21),
                                                    ('Vila Nova do Sul', 21),
                                                    ('Vista Alegre', 21),
                                                    ('Vista Alegre do Prata', 21),
                                                    ('Vista Gaúcha', 21),
                                                    ('Vitória das Missões', 21),
                                                    ('Westfália', 21),
                                                    ('Xangri-lá', 21);
