INSERT INTO cidade (nome_cidade, cidade_estado) VALUES
                                                    ('Abadia dos Dourados', 13),
                                                    ('Abaeté', 13),
                                                    ('Abre Campo', 13),
                                                    ('Acaiaca', 13),
                                                    ('Açucena', 13),
                                                    ('Água Boa', 13),
                                                    ('Água Comprida', 13),
                                                    ('Aguanil', 13),
                                                    ('Águas Formosas', 13),
                                                    ('Águas Vermelhas', 13),
                                                    ('Aimorés', 13),
                                                    ('Aiuruoca', 13),
                                                    ('Alagoa', 13),
                                                    ('Albertina', 13),
                                                    ('Além Paraíba', 13),
                                                    ('Alfenas', 13),
                                                    ('Alfredo Vasconcelos', 13),
                                                    ('Almenara', 13),
                                                    ('Alpercata', 13),
                                                    ('Alpinópolis', 13),
                                                    ('Alterosa', 13),
                                                    ('Alto Caparaó', 13),
                                                    ('Alto Jequitibá', 13),
                                                    ('Alto Rio Doce', 13),
                                                    ('Alvarenga', 13),
                                                    ('Alvinópolis', 13),
                                                    ('Alvorada de Minas', 13),
                                                    ('Amparo do Serra', 13),
                                                    ('Andradas', 13),
                                                    ('Andrelândia', 13),
                                                    ('Angelândia', 13),
                                                    ('Antônio Carlos', 13),
                                                    ('Antônio Dias', 13),
                                                    ('Antônio Prado de Minas', 13),
                                                    ('Araçaí', 13),
                                                    ('Aracitaba', 13),
                                                    ('Araçuaí', 13),
                                                    ('Araguari', 13),
                                                    ('Arantina', 13),
                                                    ('Araponga', 13),
                                                    ('Araporã', 13),
                                                    ('Arapuá', 13),
                                                    ('Araújos', 13),
                                                    ('Araxá', 13),
                                                    ('Arceburgo', 13),
                                                    ('Arcos', 13),
                                                    ('Areado', 13),
                                                    ('Argirita', 13),
                                                    ('Aricanduva', 13),
                                                    ('Arinos', 13),
                                                    ('Astolfo Dutra', 13),
                                                    ('Ataléia', 13),
                                                    ('Augusto de Lima', 13),
                                                    ('Baependi', 13),
                                                    ('Baldim', 13),
                                                    ('Bambuí', 13),
                                                    ('Bandeira', 13),
                                                    ('Bandeira do Sul', 13),
                                                    ('Barão de Cocais', 13),
                                                    ('Barão de Monte Alto', 13),
                                                    ('Barbacena', 13),
                                                    ('Barra Longa', 13),
                                                    ('Barroso', 13),
                                                    ('Bela Vista de Minas', 13),
                                                    ('Belmiro Braga', 13),
                                                    ('Belo Horizonte', 13),
                                                    ('Belo Oriente', 13),
                                                    ('Belo Vale', 13),
                                                    ('Berilo', 13),
                                                    ('Berizal', 13),
                                                    ('Bertópolis', 13),
                                                    ('Betim', 13),
                                                    ('Bias Fortes', 13),
                                                    ('Bicas', 13),
                                                    ('Biquinhas', 13),
                                                    ('Boa Esperança', 13),
                                                    ('Bocaina de Minas', 13),
                                                    ('Bocaiúva', 13),
                                                    ('Bom Despacho', 13),
                                                    ('Bom Jardim de Minas', 13),
                                                    ('Bom Jesus da Penha', 13),
                                                    ('Bom Jesus do Amparo', 13),
                                                    ('Bom Jesus do Galho', 13),
                                                    ('Bom Repouso', 13),
                                                    ('Bom Sucesso', 13),
                                                    ('Bonfim', 13),
                                                    ('Bonfinópolis de Minas', 13),
                                                    ('Bonito de Minas', 13),
                                                    ('Borda da Mata', 13),
                                                    ('Botelhos', 13),
                                                    ('Botumirim', 13),
                                                    ('Brás Pires', 13),
                                                    ('Brasilândia de Minas', 13),
                                                    ('Brasília de Minas', 13),
                                                    ('Brasópolis', 13),
                                                    ('Braúnas', 13),
                                                    ('Brumadinho', 13),
                                                    ('Bueno Brandão', 13),
                                                    ('Buenópolis', 13),
                                                    ('Bugre', 13),
                                                    ('Buritis', 13),
                                                    ('Buritizeiro', 13),
                                                    ('Cabeceira Grande', 13),
                                                    ('Cabo Verde', 13),
                                                    ('Cachoeira da Prata', 13),
                                                    ('Cachoeira de Minas', 13),
                                                    ('Cachoeira de Pajeú', 13),
                                                    ('Cachoeira Dourada', 13),
                                                    ('Caetanópolis', 13),
                                                    ('Caeté', 13),
                                                    ('Caiana', 13),
                                                    ('Cajuri', 13),
                                                    ('Caldas', 13),
                                                    ('Camacho', 13),
                                                    ('Camanducaia', 13),
                                                    ('Cambuí', 13),
                                                    ('Cambuquira', 13),
                                                    ('Campanário', 13),
                                                    ('Campanha', 13),
                                                    ('Campestre', 13),
                                                    ('Campina Verde', 13),
                                                    ('Campo Azul', 13),
                                                    ('Campo Belo', 13),
                                                    ('Campo do Meio', 13),
                                                    ('Campo Florido', 13),
                                                    ('Campos Altos', 13),
                                                    ('Campos Gerais', 13),
                                                    ('Cana Verde', 13),
                                                    ('Canaã', 13),
                                                    ('Canápolis', 13),
                                                    ('Candeias', 13),
                                                    ('Cantagalo', 13),
                                                    ('Caparaó', 13),
                                                    ('Capela Nova', 13),
                                                    ('Capelinha', 13),
                                                    ('Capetinga', 13),
                                                    ('Capim Branco', 13),
                                                    ('Capinópolis', 13),
                                                    ('Capitão Andrade', 13),
                                                    ('Capitão Enéas', 13),
                                                    ('Capitólio', 13),
                                                    ('Caputira', 13),
                                                    ('Caraí', 13),
                                                    ('Caranaíba', 13),
                                                    ('Carandaí', 13),
                                                    ('Carangola', 13),
                                                    ('Caratinga', 13),
                                                    ('Carbonita', 13),
                                                    ('Careaçu', 13),
                                                    ('Carlos Chagas', 13),
                                                    ('Carmésia', 13),
                                                    ('Carmo da Cachoeira', 13),
                                                    ('Carmo da Mata', 13),
                                                    ('Carmo de Minas', 13),
                                                    ('Carmo do Cajuru', 13),
                                                    ('Carmo do Paranaíba', 13),
                                                    ('Carmo do Rio Claro', 13),
                                                    ('Carmópolis de Minas', 13),
                                                    ('Carneirinho', 13),
                                                    ('Carrancas', 13),
                                                    ('Carvalhópolis', 13),
                                                    ('Carvalhos', 13),
                                                    ('Casa Grande', 13),
                                                    ('Cascalho Rico', 13),
                                                    ('Cássia', 13),
                                                    ('Cataguases', 13),
                                                    ('Catas Altas', 13),
                                                    ('Catas Altas da Noruega', 13),
                                                    ('Catuji', 13),
                                                    ('Catuti', 13),
                                                    ('Caxambu', 13),
                                                    ('Cedro do Abaeté', 13),
                                                    ('Central de Minas', 13),
                                                    ('Centralina', 13),
                                                    ('Chácara', 13),
                                                    ('Chalé', 13),
                                                    ('Chapada do Norte', 13),
                                                    ('Chapada Gaúcha', 13),
                                                    ('Chiador', 13),
                                                    ('Cipotânea', 13),
                                                    ('Claraval', 13),
                                                    ('Claro dos Poções', 13),
                                                    ('Cláudio', 13),
                                                    ('Coimbra', 13),
                                                    ('Coluna', 13),
                                                    ('Comendador Gomes', 13),
                                                    ('Comercinho', 13),
                                                    ('Conceição da Aparecida', 13),
                                                    ('Conceição da Barra de Minas', 13),
                                                    ('Conceição das Alagoas', 13),
                                                    ('Conceição das Pedras', 13),
                                                    ('Conceição de Ipanema', 13),
                                                    ('Conceição do Mato Dentro', 13),
                                                    ('Conceição do Pará', 13),
                                                    ('Conceição do Rio Verde', 13),
                                                    ('Conceição dos Ouros', 13),
                                                    ('Cônego Marinho', 13),
                                                    ('Confins', 13),
                                                    ('Congonhal', 13),
                                                    ('Congonhas', 13),
                                                    ('Congonhas do Norte', 13),
                                                    ('Conquista', 13),
                                                    ('Conselheiro Lafaiete', 13),
                                                    ('Conselheiro Pena', 13),
                                                    ('Consolação', 13),
                                                    ('Contagem', 13),
                                                    ('Coqueiral', 13),
                                                    ('Coração de Jesus', 13),
                                                    ('Cordisburgo', 13),
                                                    ('Cordislândia', 13),
                                                    ('Corinto', 13),
                                                    ('Coroaci', 13),
                                                    ('Coromandel', 13),
                                                    ('Coronel Fabriciano', 13),
                                                    ('Coronel Murta', 13),
                                                    ('Coronel Pacheco', 13),
                                                    ('Coronel Xavier Chaves', 13),
                                                    ('Córrego Danta', 13),
                                                    ('Córrego do Bom Jesus', 13),
                                                    ('Córrego Fundo', 13),
                                                    ('Córrego Novo', 13),
                                                    ('Couto de Magalhães de Minas', 13),
                                                    ('Crisólita', 13),
                                                    ('Cristais', 13),
                                                    ('Cristália', 13),
                                                    ('Cristiano Otoni', 13),
                                                    ('Cristina', 13),
                                                    ('Crucilândia', 13),
                                                    ('Cruzeiro da Fortaleza', 13),
                                                    ('Cruzília', 13),
                                                    ('Cuparaque', 13),
                                                    ('Curral de Dentro', 13),
                                                    ('Curvelo', 13),
                                                    ('Datas', 13),
                                                    ('Delfim Moreira', 13),
                                                    ('Delfinópolis', 13),
                                                    ('Delta', 13),
                                                    ('Descoberto', 13),
                                                    ('Desterro de Entre Rios', 13),
                                                    ('Desterro do Melo', 13),
                                                    ('Diamantina', 13),
                                                    ('Diogo de Vasconcelos', 13),
                                                    ('Dionísio', 13),
                                                    ('Divinésia', 13),
                                                    ('Divino', 13),
                                                    ('Divino das Laranjeiras', 13),
                                                    ('Divinolândia de Minas', 13),
                                                    ('Divinópolis', 13),
                                                    ('Divisa Alegre', 13),
                                                    ('Divisa Nova', 13),
                                                    ('Divisópolis', 13),
                                                    ('Dom Bosco', 13),
                                                    ('Dom Cavati', 13),
                                                    ('Dom Joaquim', 13),
                                                    ('Dom Silvério', 13),
                                                    ('Dom Viçoso', 13),
                                                    ('Dona Euzébia', 13),
                                                    ('Dores de Campos', 13),
                                                    ('Dores de Guanhães', 13),
                                                    ('Dores do Indaiá', 13),
                                                    ('Dores do Turvo', 13),
                                                    ('Doresópolis', 13),
                                                    ('Douradoquara', 13),
                                                    ('Durandé', 13),
                                                    ('Elói Mendes', 13),
                                                    ('Engenheiro Caldas', 13),
                                                    ('Engenheiro Navarro', 13),
                                                    ('Entre Folhas', 13),
                                                    ('Entre Rios de Minas', 13),
                                                    ('Ervália', 13),
                                                    ('Esmeraldas', 13),
                                                    ('Espera Feliz', 13),
                                                    ('Espinosa', 13),
                                                    ('Espírito Santo do Dourado', 13),
                                                    ('Estiva', 13),
                                                    ('Estrela Dalva', 13),
                                                    ('Estrela do Indaiá', 13),
                                                    ('Estrela do Sul', 13),
                                                    ('Eugenópolis', 13),
                                                    ('Ewbank da Câmara', 13),
                                                    ('Extrema', 13),
                                                    ('Fama', 13),
                                                    ('Faria Lemos', 13),
                                                    ('Felício dos Santos', 13),
                                                    ('Felisburgo', 13),
                                                    ('Felixlândia', 13),
                                                    ('Fernandes Tourinho', 13),
                                                    ('Ferros', 13),
                                                    ('Fervedouro', 13),
                                                    ('Florestal', 13),
                                                    ('Formiga', 13),
                                                    ('Formoso', 13),
                                                    ('Fortaleza de Minas', 13),
                                                    ('Fortuna de Minas', 13),
                                                    ('Francisco Badaró', 13),
                                                    ('Francisco Dumont', 13),
                                                    ('Francisco Sá', 13),
                                                    ('Franciscópolis', 13),
                                                    ('Frei Gaspar', 13),
                                                    ('Frei Inocêncio', 13),
                                                    ('Frei Lagonegro', 13),
                                                    ('Fronteira', 13),
                                                    ('Fronteira dos Vales', 13),
                                                    ('Fruta de Leite', 13),
                                                    ('Frutal', 13),
                                                    ('Funilândia', 13),
                                                    ('Galiléia', 13),
                                                    ('Gameleiras', 13),
                                                    ('Glaucilândia', 13),
                                                    ('Goiabeira', 13),
                                                    ('Goianá', 13),
                                                    ('Gonçalves', 13),
                                                    ('Gonzaga', 13),
                                                    ('Gouveia', 13),
                                                    ('Governador Valadares', 13),
                                                    ('Grão Mogol', 13),
                                                    ('Grupiara', 13),
                                                    ('Guanhães', 13),
                                                    ('Guapé', 13),
                                                    ('Guaraciaba', 13),
                                                    ('Guaraciama', 13),
                                                    ('Guaranésia', 13),
                                                    ('Guarani', 13),
                                                    ('Guarará', 13),
                                                    ('Guarda-Mor', 13),
                                                    ('Guaxupé', 13),
                                                    ('Guidoval', 13),
                                                    ('Guimarânia', 13),
                                                    ('Guiricema', 13),
                                                    ('Gurinhatã', 13),
                                                    ('Heliodora', 13),
                                                    ('Iapu', 13),
                                                    ('Ibertioga', 13),
                                                    ('Ibiá', 13),
                                                    ('Ibiaí', 13),
                                                    ('Ibiracatu', 13),
                                                    ('Ibiraci', 13),
                                                    ('Ibirité', 13),
                                                    ('Ibitiúra de Minas', 13),
                                                    ('Ibituruna', 13),
                                                    ('Icaraí de Minas', 13),
                                                    ('Igarapé', 13),
                                                    ('Igaratinga', 13),
                                                    ('Iguatama', 13),
                                                    ('Ijaci', 13),
                                                    ('Ilicínea', 13),
                                                    ('Imbé de Minas', 13),
                                                    ('Inconfidentes', 13),
                                                    ('Indaiabira', 13),
                                                    ('Indianópolis', 13),
                                                    ('Ingai', 13),
                                                    ('Inhapim', 13),
                                                    ('Inhaúma', 13),
                                                    ('Inimutaba', 13),
                                                    ('Ipaba', 13),
                                                    ('Ipanema', 13),
                                                    ('Ipatinga', 13),
                                                    ('Ipiaçu', 13),
                                                    ('Ipuiúna', 13),
                                                    ('Iraí de Minas', 13),
                                                    ('Itabira', 13),
                                                    ('Itabirinha', 13),
                                                    ('Itabirito', 13),
                                                    ('Itacambira', 13),
                                                    ('Itacarambi', 13),
                                                    ('Itaguara', 13),
                                                    ('Itaipé', 13),
                                                    ('Itajubá', 13),
                                                    ('Itamarandiba', 13),
                                                    ('Itamarati de Minas', 13),
                                                    ('Itambacuri', 13),
                                                    ('Itambé do Mato Dentro', 13),
                                                    ('Itamogi', 13),
                                                    ('Itamonte', 13),
                                                    ('Itanhandu', 13),
                                                    ('Itanhomi', 13),
                                                    ('Itaobim', 13),
                                                    ('Itapagipe', 13),
                                                    ('Itapecerica', 13),
                                                    ('Itapeva', 13),
                                                    ('Itatiaiuçu', 13),
                                                    ('Itaú de Minas', 13),
                                                    ('Itaúna', 13),
                                                    ('Itaverava', 13),
                                                    ('Itinga', 13),
                                                    ('Itueta', 13),
                                                    ('Ituiutaba', 13),
                                                    ('Itumirim', 13),
                                                    ('Iturama', 13),
                                                    ('Itutinga', 13),
                                                    ('Jaboticatubas', 13),
                                                    ('Jacinto', 13),
                                                    ('Jacuí', 13),
                                                    ('Jacutinga', 13),
                                                    ('Jaguaraçu', 13),
                                                    ('Jaíba', 13),
                                                    ('Jampruca', 13),
                                                    ('Janaúba', 13),
                                                    ('Januária', 13),
                                                    ('Japaraíba', 13),
                                                    ('Japonvar', 13),
                                                    ('Jeceaba', 13),
                                                    ('Jenipapo de Minas', 13),
                                                    ('Jequeri', 13),
                                                    ('Jequitaí', 13),
                                                    ('Jequitibá', 13),
                                                    ('Jequitinhonha', 13),
                                                    ('Jesuânia', 13),
                                                    ('Joaíma', 13),
                                                    ('Joanésia', 13),
                                                    ('João Monlevade', 13),
                                                    ('João Pinheiro', 13),
                                                    ('Joaquim Felício', 13),
                                                    ('Jordânia', 13),
                                                    ('José Gonçalves de Minas', 13),
                                                    ('José Raydan', 13),
                                                    ('Josenópolis', 13),
                                                    ('Juatuba', 13),
                                                    ('Juiz de Fora', 13),
                                                    ('Juramento', 13),
                                                    ('Juruaia', 13),
                                                    ('Juvenília', 13),
                                                    ('Ladainha', 13),
                                                    ('Lagamar', 13),
                                                    ('Lagoa da Prata', 13),
                                                    ('Lagoa dos Patos', 13),
                                                    ('Lagoa Dourada', 13),
                                                    ('Lagoa Formosa', 13),
                                                    ('Lagoa Grande', 13),
                                                    ('Lagoa Santa', 13),
                                                    ('Lagoa Seca de Itaúna', 13),
                                                    ('Lajinha', 13),
                                                    ('Lambari', 13),
                                                    ('Lamim', 13),
                                                    ('Laranjal', 13),
                                                    ('Lassance', 13),
                                                    ('Lavras', 13),
                                                    ('Leandro Ferreira', 13),
                                                    ('Leme do Prado', 13),
                                                    ('Leopoldina', 13),
                                                    ('Liberdade', 13),
                                                    ('Lima Duarte', 13),
                                                    ('Limeira do Oeste', 13),
                                                    ('Lontra', 13),
                                                    ('Luisburgo', 13),
                                                    ('Luislândia', 13),
                                                    ('Luminárias', 13),
                                                    ('Luz', 13),
                                                    ('Machacalis', 13),
                                                    ('Machado', 13),
                                                    ('Madre de Deus de Minas', 13),
                                                    ('Malacacheta', 13),
                                                    ('Mamonas', 13),
                                                    ('Manga', 13),
                                                    ('Manhuaçu', 13),
                                                    ('Manhumirim', 13),
                                                    ('Mantena', 13),
                                                    ('Mar de Espanha', 13),
                                                    ('Maravilhas', 13),
                                                    ('Maria da Fé', 13),
                                                    ('Mariana', 13),
                                                    ('Marilac', 13),
                                                    ('Mário Campos', 13),
                                                    ('Maripá de Minas', 13),
                                                    ('Marliéria', 13),
                                                    ('Marmelópolis', 13),
                                                    ('Martinho Campos', 13),
                                                    ('Martins Soares', 13),
                                                    ('Mata Verde', 13),
                                                    ('Materlândia', 13),
                                                    ('Mateus Leme', 13),
                                                    ('Mathias Lobato', 13),
                                                    ('Matias Barbosa', 13),
                                                    ('Matias Cardoso', 13),
                                                    ('Matipó', 13),
                                                    ('Mato Verde', 13),
                                                    ('Matozinhos', 13),
                                                    ('Matutina', 13),
                                                    ('Medeiros', 13),
                                                    ('Medina', 13),
                                                    ('Mendes Pimentel', 13),
                                                    ('Mercês', 13),
                                                    ('Mesquita', 13),
                                                    ('Minas Novas', 13),
                                                    ('Minduri', 13),
                                                    ('Mirabela', 13),
                                                    ('Miradouro', 13),
                                                    ('Miraí', 13),
                                                    ('Miravânia', 13),
                                                    ('Moeda', 13),
                                                    ('Moema', 13),
                                                    ('Monjolos', 13),
                                                    ('Monsenhor Paulo', 13),
                                                    ('Montalvânia', 13),
                                                    ('Monte Alegre de Minas', 13),
                                                    ('Monte Azul', 13),
                                                    ('Monte Belo', 13),
                                                    ('Monte Carmelo', 13),
                                                    ('Monte Formoso', 13),
                                                    ('Monte Santo de Minas', 13),
                                                    ('Monte Sião', 13),
                                                    ('Montes Claros', 13),
                                                    ('Montezuma', 13),
                                                    ('Morada Nova de Minas', 13),
                                                    ('Morro da Garça', 13),
                                                    ('Morro do Pilar', 13),
                                                    ('Munhoz', 13),
                                                    ('Muriaé', 13),
                                                    ('Mutum', 13),
                                                    ('Muzambinho', 13),
                                                    ('Nacip Raydan', 13),
                                                    ('Nanuque', 13),
                                                    ('Naque', 13),
                                                    ('Natalândia', 13),
                                                    ('Natércia', 13),
                                                    ('Nazareno', 13),
                                                    ('Nepomuceno', 13),
                                                    ('Ninheira', 13),
                                                    ('Nova Belém', 13),
                                                    ('Nova Era', 13),
                                                    ('Nova Lima', 13),
                                                    ('Nova Módica', 13),
                                                    ('Nova Ponte', 13),
                                                    ('Nova Porteirinha', 13),
                                                    ('Nova Resende', 13),
                                                    ('Nova Serrana', 13),
                                                    ('Nova União', 13),
                                                    ('Novo Cruzeiro', 13),
                                                    ('Novo Oriente de Minas', 13),
                                                    ('Novorizonte', 13),
                                                    ('Olaria', 13),
                                                    ('Olhos-d`Água', 13),
                                                    ('Olímpio Noronha', 13),
                                                    ('Oliveira', 13),
                                                    ('Oliveira Fortes', 13),
                                                    ('Onça de Pitangui', 13),
                                                    ('Oratórios', 13),
                                                    ('Orizânia', 13),
                                                    ('Ouro Branco', 13),
                                                    ('Ouro Fino', 13),
                                                    ('Ouro Preto', 13),
                                                    ('Ouro Verde de Minas', 13),
                                                    ('Padre Carvalho', 13),
                                                    ('Padre Paraíso', 13),
                                                    ('Pai Pedro', 13),
                                                    ('Paineiras', 13),
                                                    ('Pains', 13),
                                                    ('Paiva', 13),
                                                    ('Palma', 13),
                                                    ('Palmópolis', 13),
                                                    ('Papagaios', 13),
                                                    ('Pará de Minas', 13),
                                                    ('Paracatu', 13),
                                                    ('Paraguaçu', 13),
                                                    ('Paraisópolis', 13),
                                                    ('Paraopeba', 13),
                                                    ('Passa Quatro', 13),
                                                    ('Passa Tempo', 13),
                                                    ('Passa-Vinte', 13),
                                                    ('Passabém', 13),
                                                    ('Passos', 13),
                                                    ('Patis', 13),
                                                    ('Patos de Minas', 13),
                                                    ('Patrocínio', 13),
                                                    ('Patrocínio do Muriaé', 13),
                                                    ('Paula Cândido', 13),
                                                    ('Paulistas', 13),
                                                    ('Pavão', 13),
                                                    ('Peçanha', 13),
                                                    ('Pedra Azul', 13),
                                                    ('Pedra Bonita', 13),
                                                    ('Pedra do Anta', 13),
                                                    ('Pedra do Indaiá', 13),
                                                    ('Pedra Dourada', 13),
                                                    ('Pedralva', 13),
                                                    ('Pedras de Maria da Cruz', 13),
                                                    ('Pedrinópolis', 13),
                                                    ('Pedro Leopoldo', 13),
                                                    ('Pedro Teixeira', 13),
                                                    ('Pequeri', 13),
                                                    ('Pequi', 13),
                                                    ('Perdigão', 13),
                                                    ('Perdizes', 13),
                                                    ('Perdões', 13),
                                                    ('Periquito', 13),
                                                    ('Pescador', 13),
                                                    ('Piau', 13),
                                                    ('Piedade de Caratinga', 13),
                                                    ('Piedade de Ponte Nova', 13),
                                                    ('Piedade do Rio Grande', 13),
                                                    ('Piedade dos Gerais', 13),
                                                    ('Pimenta', 13),
                                                    ('Pingo-d`Água', 13),
                                                    ('Pintópolis', 13),
                                                    ('Piracema', 13),
                                                    ('Pirajuba', 13),
                                                    ('Piranga', 13),
                                                    ('Piranguçu', 13),
                                                    ('Piranguinho', 13),
                                                    ('Pirapetinga', 13),
                                                    ('Pirapora', 13),
                                                    ('Piraúba', 13),
                                                    ('Pitangui', 13),
                                                    ('Piumhi', 13),
                                                    ('Planura', 13),
                                                    ('Poço Fundo', 13),
                                                    ('Poços de Caldas', 13),
                                                    ('Pocrane', 13),
                                                    ('Pompéu', 13),
                                                    ('Ponte Nova', 13),
                                                    ('Ponto Chique', 13),
                                                    ('Ponto dos Volantes', 13),
                                                    ('Porteirinha', 13),
                                                    ('Porto Firme', 13),
                                                    ('Poté', 13),
                                                    ('Pouso Alegre', 13),
                                                    ('Pouso Alto', 13),
                                                    ('Prados', 13),
                                                    ('Prata', 13),
                                                    ('Pratápolis', 13),
                                                    ('Pratinha', 13),
                                                    ('Presidente Bernardes', 13),
                                                    ('Presidente Juscelino', 13),
                                                    ('Presidente Kubitschek', 13),
                                                    ('Presidente Olegário', 13),
                                                    ('Prudente de Morais', 13),
                                                    ('Quartel Geral', 13),
                                                    ('Queluzito', 13),
                                                    ('Raposos', 13),
                                                    ('Raul Soares', 13),
                                                    ('Recreio', 13),
                                                    ('Reduto', 13),
                                                    ('Resende Costa', 13),
                                                    ('Resplendor', 13),
                                                    ('Ressaquinha', 13),
                                                    ('Riachinho', 13),
                                                    ('Riacho dos Machados', 13),
                                                    ('Ribeirão das Neves', 13),
                                                    ('Ribeirão Vermelho', 13),
                                                    ('Rio Acima', 13),
                                                    ('Rio Casca', 13),
                                                    ('Rio do Prado', 13),
                                                    ('Rio Doce', 13),
                                                    ('Rio Espera', 13),
                                                    ('Rio Manso', 13),
                                                    ('Rio Novo', 13),
                                                    ('Rio Paranaíba', 13),
                                                    ('Rio Pardo de Minas', 13),
                                                    ('Rio Piracicaba', 13),
                                                    ('Rio Pomba', 13),
                                                    ('Rio Preto', 13),
                                                    ('Rio Vermelho', 13),
                                                    ('Ritápolis', 13),
                                                    ('Rochedo de Minas', 13),
                                                    ('Rodeiro', 13),
                                                    ('Romaria', 13),
                                                    ('Rosário da Limeira', 13),
                                                    ('Rubelita', 13),
                                                    ('Rubim', 13),
                                                    ('Sabará', 13),
                                                    ('Sabinópolis', 13),
                                                    ('Sacramento', 13),
                                                    ('Salinas', 13),
                                                    ('Salto da Divisa', 13),
                                                    ('Santa Bárbara', 13),
                                                    ('Santa Bárbara do Leste', 13),
                                                    ('Santa Bárbara do Monte Verde', 13),
                                                    ('Santa Bárbara do Tugúrio', 13),
                                                    ('Santa Cruz de Minas', 13),
                                                    ('Santa Cruz de Salinas', 13),
                                                    ('Santa Cruz do Escalvado', 13),
                                                    ('Santa Efigênia de Minas', 13),
                                                    ('Santa Fé de Minas', 13),
                                                    ('Santa Helena de Minas', 13),
                                                    ('Santa Juliana', 13),
                                                    ('Santa Luzia', 13),
                                                    ('Santa Margarida', 13),
                                                    ('Santa Maria de Itabira', 13),
                                                    ('Santa Maria do Salto', 13),
                                                    ('Santa Maria do Suaçuí', 13),
                                                    ('Santa Rita de Caldas', 13),
                                                    ('Santa Rita de Ibitipoca', 13),
                                                    ('Santa Rita de Jacutinga', 13),
                                                    ('Santa Rita de Minas', 13),
                                                    ('Santa Rita do Itueto', 13),
                                                    ('Santa Rita do Sapucaí', 13),
                                                    ('Santa Rosa da Serra', 13),
                                                    ('Santa Vitória', 13),
                                                    ('Santana da Vargem', 13),
                                                    ('Santana de Cataguases', 13),
                                                    ('Santana de Pirapama', 13),
                                                    ('Santana do Deserto', 13),
                                                    ('Santana do Garambéu', 13),
                                                    ('Santana do Jacaré', 13),
                                                    ('Santana do Manhuaçu', 13),
                                                    ('Santana do Paraíso', 13),
                                                    ('Santana do Riacho', 13),
                                                    ('Santana dos Montes', 13),
                                                    ('Santo Antônio do Amparo', 13),
                                                    ('Santo Antônio do Aventureiro', 13),
                                                    ('Santo Antônio do Grama', 13),
                                                    ('Santo Antônio do Itambé', 13),
                                                    ('Santo Antônio do Jacinto', 13),
                                                    ('Santo Antônio do Monte', 13),
                                                    ('Santo Antônio do Retiro', 13),
                                                    ('Santo Antônio do Rio Abaixo', 13),
                                                    ('Santo Hipólito', 13),
                                                    ('Santos Dumont', 13),
                                                    ('São Bento Abade', 13),
                                                    ('São Brás do Suaçuí', 13),
                                                    ('São Domingos das Dores', 13),
                                                    ('São Domingos do Prata', 13),
                                                    ('São Félix de Minas', 13),
                                                    ('São Francisco', 13),
                                                    ('São Francisco de Paula', 13),
                                                    ('São Francisco de Sales', 13),
                                                    ('São Francisco do Glória', 13),
                                                    ('São Geraldo', 13),
                                                    ('São Geraldo da Piedade', 13),
                                                    ('São Geraldo do Baixio', 13),
                                                    ('São Gonçalo do Abaeté', 13),
                                                    ('São Gonçalo do Pará', 13),
                                                    ('São Gonçalo do Rio Abaixo', 13),
                                                    ('São Gonçalo do Rio Preto', 13),
                                                    ('São Gonçalo do Sapucaí', 13),
                                                    ('São Gotardo', 13),
                                                    ('São João Batista do Glória', 13),
                                                    ('São João da Lagoa', 13),
                                                    ('São João da Mata', 13),
                                                    ('São João da Ponte', 13),
                                                    ('São João das Missões', 13),
                                                    ('São João del Rei', 13),
                                                    ('São João do Manhuaçu', 13),
                                                    ('São João do Manteninha', 13),
                                                    ('São João do Oriente', 13),
                                                    ('São João do Pacuí', 13),
                                                    ('São João do Paraíso', 13),
                                                    ('São João Evangelista', 13),
                                                    ('São João Nepomuceno', 13),
                                                    ('São Joaquim de Bicas', 13),
                                                    ('São José da Barra', 13),
                                                    ('São José da Lapa', 13),
                                                    ('São José da Safira', 13),
                                                    ('São José da Varginha', 13),
                                                    ('São José do Alegre', 13),
                                                    ('São José do Divino', 13),
                                                    ('São José do Goiabal', 13),
                                                    ('São José do Jacuri', 13),
                                                    ('São José do Mantimento', 13),
                                                    ('São Lourenço', 13),
                                                    ('São Miguel do Anta', 13),
                                                    ('São Pedro da União', 13),
                                                    ('São Pedro do Suaçuí', 13),
                                                    ('São Pedro dos Ferros', 13),
                                                    ('São Romão', 13),
                                                    ('São Roque de Minas', 13),
                                                    ('São Sebastião da Bela Vista', 13),
                                                    ('São Sebastião da Vargem Alegre', 13),
                                                    ('São Sebastião do Anta', 13),
                                                    ('São Sebastião do Maranhão', 13),
                                                    ('São Sebastião do Oeste', 13),
                                                    ('São Sebastião do Paraíso', 13),
                                                    ('São Sebastião do Rio Preto', 13),
                                                    ('São Sebastião do Rio Verde', 13),
                                                    ('São Thomé das Letras', 13),
                                                    ('São Tiago', 13),
                                                    ('São Tomás de Aquino', 13),
                                                    ('São Vicente de Minas', 13),
                                                    ('Sapucaí-Mirim', 13),
                                                    ('Sardoá', 13),
                                                    ('Sarzedo', 13),
                                                    ('Sem-Peixe', 13),
                                                    ('Senador Amaral', 13),
                                                    ('Senador Cortes', 13),
                                                    ('Senador Firmino', 13),
                                                    ('Senador José Bento', 13),
                                                    ('Senador Modestino Gonçalves', 13),
                                                    ('Senhora de Oliveira', 13),
                                                    ('Senhora do Porto', 13),
                                                    ('Senhora dos Remédios', 13),
                                                    ('Sericita', 13),
                                                    ('Seritinga', 13),
                                                    ('Serra Azul de Minas', 13),
                                                    ('Serra da Saudade', 13),
                                                    ('Serra do Salitre', 13),
                                                    ('Serra dos Aimorés', 13),
                                                    ('Serrania', 13),
                                                    ('Serranópolis de Minas', 13),
                                                    ('Serranos', 13),
                                                    ('Serro', 13),
                                                    ('Sete Lagoas', 13),
                                                    ('Setubinha', 13),
                                                    ('Silveirânia', 13),
                                                    ('Silvianópolis', 13),
                                                    ('Simão Pereira', 13),
                                                    ('Simonésia', 13),
                                                    ('Sobrália', 13),
                                                    ('Soledade de Minas', 13),
                                                    ('Tabuleiro', 13),
                                                    ('Taiobeiras', 13),
                                                    ('Taparuba', 13),
                                                    ('Tapira', 13),
                                                    ('Tapiraí', 13),
                                                    ('Taquaraçu de Minas', 13),
                                                    ('Tarumirim', 13),
                                                    ('Teixeiras', 13),
                                                    ('Teófilo Otoni', 13),
                                                    ('Timóteo', 13),
                                                    ('Tiradentes', 13),
                                                    ('Tiros', 13),
                                                    ('Tocantins', 13),
                                                    ('Tocos do Moji', 13),
                                                    ('Toledo', 13),
                                                    ('Tombos', 13),
                                                    ('Três Corações', 13),
                                                    ('Três Marias', 13),
                                                    ('Três Pontas', 13),
                                                    ('Tumiritinga', 13),
                                                    ('Tupaciguara', 13),
                                                    ('Turmalina', 13),
                                                    ('Turvolândia', 13),
                                                    ('Ubá', 13),
                                                    ('Ubaí', 13),
                                                    ('Ubaporanga', 13),
                                                    ('Uberaba', 13),
                                                    ('Uberlândia', 13),
                                                    ('Umburatiba', 13),
                                                    ('Unaí', 13),
                                                    ('União de Minas', 13),
                                                    ('Uruana de Minas', 13),
                                                    ('Urucânia', 13),
                                                    ('Urucuia', 13),
                                                    ('Vargem Alegre', 13),
                                                    ('Vargem Bonita', 13),
                                                    ('Vargem Grande do Rio Pardo', 13),
                                                    ('Varginha', 13),
                                                    ('Varjão de Minas', 13),
                                                    ('Várzea da Palma', 13),
                                                    ('Varzelândia', 13),
                                                    ('Vazante', 13),
                                                    ('Verdelândia', 13),
                                                    ('Veredinha', 13),
                                                    ('Veríssimo', 13),
                                                    ('Vermelho Novo', 13),
                                                    ('Vespasiano', 13),
                                                    ('Viçosa', 13),
                                                    ('Vieiras', 13),
                                                    ('Virgem da Lapa', 13),
                                                    ('Virgínia', 13),
                                                    ('Virginópolis', 13),
                                                    ('Virgolândia', 13),
                                                    ('Visconde do Rio Branco', 13),
                                                    ('Volta Grande', 13),
                                                    ('Wenceslau Braz', 13);