INSERT INTO cidade (nome_cidade, cidade_estado) VALUES
                                                    ('Abdon Batista', 24),
                                                    ('Abelardo Luz', 24),
                                                    ('Agrolândia', 24),
                                                    ('Agronômica', 24),
                                                    ('Água Doce', 24),
                                                    ('Águas de Chapecó', 24),
                                                    ('Águas Frias', 24),
                                                    ('Águas Mornas', 24),
                                                    ('Alfredo Wagner', 24),
                                                    ('Alto Bela Vista', 24),
                                                    ('Anchieta', 24),
                                                    ('Angelina', 24),
                                                    ('Anita Garibaldi', 24),
                                                    ('Anitápolis', 24),
                                                    ('Antônio Carlos', 24),
                                                    ('Apiúna', 24),
                                                    ('Arabutã', 24),
                                                    ('Araquari', 24),
                                                    ('Araranguá', 24),
                                                    ('Armazém', 24),
                                                    ('Arroio Trinta', 24),
                                                    ('Arvoredo', 24),
                                                    ('Ascurra', 24),
                                                    ('Atalanta', 24),
                                                    ('Aurora', 24),
                                                    ('Balneário Arroio do Silva', 24),
                                                    ('Balneário Barra do Sul', 24),
                                                    ('Balneário Camboriú', 24),
                                                    ('Balneário Gaivota', 24),
                                                    ('Balneário Rincão', 24),
                                                    ('Bandeirante', 24),
                                                    ('Barra Bonita', 24),
                                                    ('Barra Velha', 24),
                                                    ('Bela Vista do Toldo', 24),
                                                    ('Belmonte', 24),
                                                    ('Benedito Novo', 24),
                                                    ('Biguaçu', 24),
                                                    ('Blumenau', 24),
                                                    ('Bocaina do Sul', 24),
                                                    ('Bom Jardim da Serra', 24),
                                                    ('Bom Jesus', 24),
                                                    ('Bom Jesus do Oeste', 24),
                                                    ('Bom Retiro', 24),
                                                    ('Bombinhas', 24),
                                                    ('Botuverá', 24),
                                                    ('Braço do Norte', 24),
                                                    ('Braço do Trombudo', 24),
                                                    ('Brunópolis', 24),
                                                    ('Brusque', 24),
                                                    ('Caçador', 24),
                                                    ('Caibi', 24),
                                                    ('Calmon', 24),
                                                    ('Camboriú', 24),
                                                    ('Campo Alegre', 24),
                                                    ('Campo Belo do Sul', 24),
                                                    ('Campo Erê', 24),
                                                    ('Campos Novos', 24),
                                                    ('Canelinha', 24),
                                                    ('Canoinhas', 24),
                                                    ('Capão Alto', 24),
                                                    ('Capinzal', 24),
                                                    ('Capivari de Baixo', 24),
                                                    ('Catanduvas', 24),
                                                    ('Caxambu do Sul', 24),
                                                    ('Celso Ramos', 24),
                                                    ('Cerro Negro', 24),
                                                    ('Chapadão do Lageado', 24),
                                                    ('Chapecó', 24),
                                                    ('Cocal do Sul', 24),
                                                    ('Concórdia', 24),
                                                    ('Cordilheira Alta', 24),
                                                    ('Coronel Freitas', 24),
                                                    ('Coronel Martins', 24),
                                                    ('Correia Pinto', 24),
                                                    ('Corupá', 24),
                                                    ('Criciúma', 24),
                                                    ('Cunha Porã', 24),
                                                    ('Cunhataí', 24),
                                                    ('Curitibanos', 24),
                                                    ('Descanso', 24),
                                                    ('Dionísio Cerqueira', 24),
                                                    ('Dona Emma', 24),
                                                    ('Doutor Pedrinho', 24),
                                                    ('Entre Rios', 24),
                                                    ('Ermo', 24),
                                                    ('Erval Velho', 24),
                                                    ('Faxinal dos Guedes', 24),
                                                    ('Flor do Sertão', 24),
                                                    ('Florianópolis', 24),
                                                    ('Formosa do Sul', 24),
                                                    ('Forquilhinha', 24),
                                                    ('Fraiburgo', 24),
                                                    ('Frei Rogério', 24),
                                                    ('Galvão', 24),
                                                    ('Garopaba', 24),
                                                    ('Garuva', 24),
                                                    ('Gaspar', 24),
                                                    ('Governador Celso Ramos', 24),
                                                    ('Grão Pará', 24),
                                                    ('Gravatal', 24),
                                                    ('Guabiruba', 24),
                                                    ('Guaraciaba', 24),
                                                    ('Guaramirim', 24),
                                                    ('Guarujá do Sul', 24),
                                                    ('Guatambú', 24),
                                                    ('Herval do Oeste', 24),
('Ibiam', 24),
('Ibicaré', 24),
('Ibirama', 24),
('Içara', 24),
('Ilhota', 24),
('Imaruí', 24),
('Imbituba', 24),
('Imbuia', 24),
('Indaial', 24),
('Iomerê', 24),
('Ipira', 24),
('Iporã do Oeste', 24),
('Ipuaçu', 24),
('Ipumirim', 24),
('Iraceminha', 24),
('Irani', 24),
('Irati', 24),
('Irineópolis', 24),
('Itá', 24),
('Itaiópolis', 24),
('Itajaí', 24),
('Itapema', 24),
('Itapiranga', 24),
('Itapoá', 24),
('Ituporanga', 24),
('Jaborá', 24),
('Jacinto Machado', 24),
('Jaguaruna', 24),
('Jaraguá do Sul', 24),
('Jardinópolis', 24),
('Joaçaba', 24),
('Joinville', 24),
('José Boiteux', 24),
('Jupiá', 24),
('Lacerdópolis', 24),
('Lages', 24),
('Laguna', 24),
('Lajeado Grande', 24),
('Laurentino', 24),
('Lauro Muller', 24),
('Lebon Régis', 24),
('Leoberto Leal', 24),
('Lindóia do Sul', 24),
('Lontras', 24),
('Luiz Alves', 24),
('Luzerna', 24),
('Macieira', 24),
('Mafra', 24),
('Major Gercino', 24),
('Major Vieira', 24),
('Maracajá', 24),
('Maravilha', 24),
('Marema', 24),
('Massaranduba', 24),
('Matos Costa', 24),
('Meleiro', 24),
('Mirim Doce', 24),
('Modelo', 24),
('Mondaí', 24),
('Monte Carlo', 24),
('Monte Castelo', 24),
('Morro da Fumaça', 24),
('Morro Grande', 24),
('Navegantes', 24),
('Nova Erechim', 24),
('Nova Itaberaba', 24),
('Nova Trento', 24),
('Nova Veneza', 24),
('Novo Horizonte', 24),
('Orleans', 24),
('Otacílio Costa', 24),
('Ouro', 24),
('Ouro Verde', 24),
('Paial', 24),
('Painel', 24),
('Palhoça', 24),
('Palma Sola', 24),
('Palmeira', 24),
('Palmitos', 24),
('Papanduva', 24),
('Paraíso', 24),
('Passo de Torres', 24),
('Passos Maia', 24),
('Paulo Lopes', 24),
('Pedras Grandes', 24),
('Penha', 24),
('Peritiba', 24),
('Petrolândia', 24),
('Pescaria Brava', 24),
('Piçarras', 24),
('Pinhalzinho', 24),
('Pinheiro Preto', 24),
('Piratuba', 24),
('Planalto Alegre', 24),
('Pomerode', 24),
('Ponte Alta', 24),
('Ponte Alta do Norte', 24),
('Ponte Serrada', 24),
('Porto Belo', 24),
('Porto União', 24),
('Pouso Redondo', 24),
('Praia Grande', 24),
('Presidente Castelo Branco', 24),
('Presidente Getúlio', 24),
('Presidente Nereu', 24),
('Princesa', 24),
('Quilombo', 24),
('Rancho Queimado', 24),
('Rio das Antas', 24),
('Rio do Campo', 24),
('Rio do Oeste', 24),
('Rio do Sul', 24),
('Rio dos Cedros', 24),
('Rio Fortuna', 24),
('Rio Negrinho', 24),
('Rio Rufino', 24),
('Riqueza', 24),
('Rodeio', 24),
('Romelândia', 24),
('Salete', 24),
('Saltinho', 24),
('Salto Veloso', 24),
('Sangão', 24),
('Santa Cecília', 24),
('Santa Helena', 24),
('Santa Rosa de Lima', 24),
('Santa Rosa do Sul', 24),
('Santa Terezinha', 24),
('Santa Terezinha do Progresso', 24),
('Santiago do Sul', 24),
('Santo Amaro da Imperatriz', 24),
('São Bento do Sul', 24),
('São Bernardino', 24),
('São Bonifácio', 24),
('São Carlos', 24),
('São Cristovão do Sul', 24),
('São Domingos', 24),
('São Francisco do Sul', 24),
('São João Batista', 24),
('São João do Itaperiú', 24),
('São João do Oeste', 24),
('São João do Sul', 24),
('São Joaquim', 24),
('São José', 24),
('São José do Cedro', 24),
('São José do Cerrito', 24),
('São Lourenço do Oeste', 24),
('São Ludgero', 24),
('São Martinho', 24),
('São Miguel da Boa Vista', 24),
('São Miguel do Oeste', 24),
('São Pedro de Alcântara', 24),
('Saudades', 24),
('Schroeder', 24),
('Seara', 24),
('Serra Alta', 24),
('Siderópolis', 24),
('Sombrio', 24),
('Sul Brasil', 24),
('Taió', 24),
('Tangará', 24),
('Tigrinhos', 24),
('Tijucas', 24),
('Timbé do Sul', 24),
('Timbó', 24),
('Timbó Grande', 24),
('Três Barras', 24),
('Treviso', 24),
('Treze de Maio', 24),
('Treze Tílias', 24),
('Trombudo Central', 24),
('Tubarão', 24),
('Tunápolis', 24),
('Turvo', 24),
('União do Oeste', 24),
('Urubici', 24),
('Urupema', 24),
('Urussanga', 24),
('Vargeão', 24),
('Vargem', 24),
('Vargem Bonita', 24),
('Vidal Ramos', 24),
('Videira', 24),
('Vitor Meireles', 24),
('Witmarsum', 24),
('Xanxerê', 24),
('Xavantina', 24),
('Xaxim', 24),
('Zortéa', 24);
