INSERT INTO cidade (nome_cidade, cidade_estado)
VALUES
    ('Abaiara', 6),
    ('Acarape', 6),
    ('Acaraú', 6),
    ('Acopiara', 6),
    ('Aiuaba', 6),
    ('Alcântaras', 6),
    ('Altaneira', 6),
    ('Alto Santo', 6),
    ('Amontada', 6),
    ('Antonina do Norte', 6),
    ('Apuiarés', 6),
    ('Aquiraz', 6),
    ('Aracati', 6),
    ('Aracoiaba', 6),
    ('Ararendá', 6),
    ('Araripe', 6),
    ('Aratuba', 6),
    ('Arneiroz', 6),
    ('Assaré', 6),
    ('Aurora', 6),
    ('Baixio', 6),
    ('Banabuiú', 6),
    ('Barbalha', 6),
    ('Barreira', 6),
    ('Barro', 6),
    ('Barroquinha', 6),
    ('Baturité', 6),
    ('Beberibe', 6),
    ('Bela Cruz', 6),
    ('Boa Viagem', 6),
    ('Brejo Santo', 6),
    ('Camocim', 6),
    ('Campos Sales', 6),
    ('Canindé', 6),
    ('Capistrano', 6),
    ('Caridade', 6),
    ('Cariré', 6),
    ('Caririaçu', 6),
    ('Cariús', 6),
    ('Carnaubal', 6),
    ('Cascavel', 6),
    ('Catarina', 6),
    ('Catunda', 6),
    ('Caucaia', 6),
    ('Cedro', 6),
    ('Chaval', 6),
    ('Choró', 6),
    ('Chorozinho', 6),
    ('Coreaú', 6),
    ('Crateús', 6),
    ('Crato', 6),
    ('Croatá', 6),
    ('Cruz', 6),
    ('Deputado Irapuan Pinheiro', 6),
    ('Ererê', 6),
    ('Eusébio', 6),
    ('Farias Brito', 6),
    ('Forquilha', 6),
    ('Fortaleza', 6),
    ('Fortim', 6),
    ('Frecheirinha', 6),
    ('General Sampaio', 6),
    ('Graça', 6),
    ('Granja', 6),
    ('Granjeiro', 6),
    ('Groaíras', 6),
    ('Guaiúba', 6),
    ('Guaraciaba do Norte', 6),
    ('Guaramiranga', 6),
    ('Hidrolândia', 6),
    ('Horizonte', 6),
    ('Ibaretama', 6),
    ('Ibiapina', 6),
    ('Ibicuitinga', 6),
    ('Icapuí', 6),
    ('Icó', 6),
    ('Iguatu', 6),
    ('Independência', 6),
    ('Ipaporanga', 6),
    ('Ipaumirim', 6),
    ('Ipu', 6),
    ('Ipueiras', 6),
    ('Iracema', 6),
    ('Irauçuba', 6),
    ('Itaiçaba', 6),
    ('Itaitinga', 6),
    ('Itapagé', 6),
    ('Itapipoca', 6),
    ('Itapiúna', 6),
    ('Itarema', 6),
    ('Itatira', 6),
    ('Jaguaretama', 6),
    ('Jaguaribara', 6),
    ('Jaguaribe', 6),
    ('Jaguaruana', 6),
    ('Jardim', 6),
    ('Jati', 6),
    ('Jijoca de Jericoacoara', 6),
    ('Juazeiro do Norte', 6),
    ('Jucás', 6),
    ('Lavras da Mangabeira', 6),
    ('Limoeiro do Norte', 6),
    ('Madalena', 6),
    ('Maracanaú', 6),
    ('Maranguape', 6),
    ('Marco', 6),
    ('Martinópole', 6),
    ('Massapê', 6),
    ('Mauriti', 6),
    ('Meruoca', 6),
    ('Milagres', 6),
    ('Milhã', 6),
    ('Miraíma', 6),
    ('Missão Velha', 6),
    ('Mombaça', 6),
    ('Monsenhor Tabosa', 6),
    ('Morada Nova', 6),
    ('Moraújo', 6),
    ('Morrinhos', 6),
    ('Mucambo', 6),
    ('Mulungu', 6),
    ('Nova Olinda', 6),
    ('Nova Russas', 6),
    ('Novo Oriente', 6),
    ('Ocara', 6),
    ('Orós', 6),
    ('Pacajus', 6),
    ('Pacatuba', 6),
    ('Pacoti', 6),
    ('Pacujá', 6),
    ('Palhano', 6),
    ('Palmácia', 6),
    ('Paracuru', 6),
    ('Paraipaba', 6),
    ('Parambu', 6),
    ('Paramoti', 6),
    ('Pedra Branca', 6),
    ('Penaforte', 6),
    ('Pentecoste', 6),
    ('Pereiro', 6),
    ('Pindoretama', 6),
    ('Piquet Carneiro', 6),
    ('Pires Ferreira', 6),
    ('Poranga', 6),
    ('Porteiras', 6),
    ('Potengi', 6),
    ('Potiretama', 6),
    ('Quiterianópolis', 6),
    ('Quixadá', 6),
    ('Quixelô', 6),
    ('Quixeramobim', 6),
    ('Quixeré', 6),
    ('Redenção', 6),
    ('Reriutaba', 6),
    ('Russas', 6),
    ('Saboeiro', 6),
    ('Salitre', 6),
    ('Santa Quitéria', 6),
    ('Santana do Acaraú', 6),
    ('Santana do Cariri', 6),
    ('São Benedito', 6),
    ('São Gonçalo do Amarante', 6),
    ('São João do Jaguaribe', 6),
    ('São Luís do Curu', 6),
    ('Senador Pompeu', 6),
    ('Senador Sá', 6),
    ('Sobral', 6),
    ('Solonópole', 6),
    ('Tabuleiro do Norte', 6),
    ('Tamboril', 6),
    ('Tarrafas', 6),
    ('Tauá', 6),
    ('Tejuçuoca', 6),
    ('Tianguá', 6),
    ('Trairi', 6),
    ('Tururu', 6),
    ('Ubajara', 6),
    ('Umari', 6),
    ('Umirim', 6),
    ('Uruburetama', 6),
    ('Uruoca', 6),
    ('Varjota', 6),
    ('Várzea Alegre', 6),
    ('Viçosa do Ceará', 6);
