INSERT INTO cidade (nome_cidade, cidade_estado)
VALUES
    ('Amparo de São Francisco', 26),
    ('Aquidabã', 26),
    ('Aracaju', 26),
    ('Arauá', 26),
    ('Areia Branca', 26),
    ('Barra dos Coqueiros', 26),
    ('Boquim', 26),
    ('Brejo Grande', 26),
    ('Campo do Brito', 26),
    ('Canhoba', 26),
    ('Canindé de São Francisco', 26),
    ('Capela', 26),
    ('Carira', 26),
    ('Carmópolis', 26),
    ('Cedro de São João', 26),
    ('Cristinápolis', 26),
    ('Cumbe', 26),
    ('Divina Pastora', 26),
    ('Estância', 26),
    ('Feira Nova', 26),
    ('Frei Paulo', 26),
    ('Gararu', 26),
    ('General Maynard', 26),
    ('Gracho Cardoso', 26),
    ('Ilha das Flores', 26),
    ('Indiaroba', 26),
    ('Itabaiana', 26),
    ('Itabaianinha', 26),
    ('Itabi', 26),
    ('Itaporanga d`Ajuda', 26),
    ('Japaratuba', 26),
    ('Japoatã', 26),
    ('Lagarto', 26),
    ('Laranjeiras', 26),
    ('Macambira', 26),
    ('Malhada dos Bois', 26),
    ('Malhador', 26),
    ('Maruim', 26),
    ('Moita Bonita', 26),
    ('Monte Alegre de Sergipe', 26),
    ('Muribeca', 26),
    ('Neópolis', 26),
    ('Nossa Senhora Aparecida', 26),
    ('Nossa Senhora da Glória', 26),
    ('Nossa Senhora das Dores', 26),
    ('Nossa Senhora de Lourdes', 26),
    ('Nossa Senhora do Socorro', 26),
    ('Pacatuba', 26),
    ('Pedra Mole', 26),
    ('Pedrinhas', 26),
    ('Pinhão', 26),
    ('Pirambu', 26),
    ('Poço Redondo', 26),
    ('Poço Verde', 26),
    ('Porto da Folha', 26),
    ('Propriá', 26),
    ('Riachão do Dantas', 26),
    ('Riachuelo', 26),
    ('Ribeirópolis', 26),
    ('Rosário do Catete', 26),
    ('Salgado', 26),
    ('Santa Luzia do Itanhy', 26),
    ('Santa Rosa de Lima', 26),
    ('Santana do São Francisco', 26),
    ('Santo Amaro das Brotas', 26),
    ('São Cristóvão', 26),
    ('São Domingos', 26),
    ('São Francisco', 26),
    ('São Miguel do Aleixo', 26),
    ('Simão Dias', 26),
    ('Siriri', 26),
    ('Telha', 26),
    ('Tobias Barreto', 26),
    ('Tomar do Geru', 26),
    ('Umbaúba', 26);
