INSERT INTO cidade (nome_cidade, cidade_estado) VALUES
                                                    ('Abadia de Goiás', 9),
                                                    ('Abadiânia', 9),
                                                    ('Acreúna', 9),
                                                    ('Adelândia', 9),
                                                    ('Água Fria de Goiás', 9),
                                                    ('Água Limpa', 9),
                                                    ('Águas Lindas de Goiás', 9),
                                                    ('Alexânia', 9),
                                                    ('Aloândia', 9),
                                                    ('Alto Horizonte', 9),
                                                    ('Alto Paraíso de Goiás', 9),
                                                    ('Alvorada do Norte', 9),
                                                    ('Amaralina', 9),
                                                    ('Americano do Brasil', 9),
                                                    ('Amorinópolis', 9),
                                                    ('Anápolis', 9),
                                                    ('Anhanguera', 9),
                                                    ('Anicuns', 9),
                                                    ('Aparecida de Goiânia', 9),
                                                    ('Aparecida do Rio Doce', 9),
                                                    ('Aporé', 9),
                                                    ('Araçu', 9),
                                                    ('Aragarças', 9),
                                                    ('Aragoiânia', 9),
                                                    ('Araguapaz', 9),
                                                    ('Arenópolis', 9),
                                                    ('Aruanã', 9),
                                                    ('Aurilândia', 9),
                                                    ('Avelinópolis', 9),
                                                    ('Baliza', 9),
                                                    ('Barro Alto', 9),
                                                    ('Bela Vista de Goiás', 9),
                                                    ('Bom Jardim de Goiás', 9),
                                                    ('Bom Jesus de Goiás', 9),
                                                    ('Bonfinópolis', 9),
                                                    ('Bonópolis', 9),
                                                    ('Brazabrantes', 9),
                                                    ('Britânia', 9),
                                                    ('Buriti Alegre', 9),
                                                    ('Buriti de Goiás', 9),
                                                    ('Buritinópolis', 9),
                                                    ('Cabeceiras', 9),
                                                    ('Cachoeira Alta', 9),
                                                    ('Cachoeira de Goiás', 9),
                                                    ('Cachoeira Dourada', 9),
                                                    ('Caçu', 9),
                                                    ('Caiapônia', 9),
                                                    ('Caldas Novas', 9),
                                                    ('Caldazinha', 9),
                                                    ('Campestre de Goiás', 9),
                                                    ('Campinaçu', 9),
                                                    ('Campinorte', 9),
                                                    ('Campo Alegre de Goiás', 9),
                                                    ('Campo Limpo de Goiás', 9),
                                                    ('Campos Belos', 9),
                                                    ('Campos Verdes', 9),
                                                    ('Carmo do Rio Verde', 9),
                                                    ('Castelândia', 9),
                                                    ('Catalão', 9),
                                                    ('Caturaí', 9),
                                                    ('Cavalcante', 9),
                                                    ('Ceres', 9),
                                                    ('Cezarina', 9),
                                                    ('Chapadão do Céu', 9),
                                                    ('Cidade Ocidental', 9),
                                                    ('Cocalzinho de Goiás', 9),
                                                    ('Colinas do Sul', 9),
                                                    ('Córrego do Ouro', 9),
                                                    ('Corumbá de Goiás', 9),
                                                    ('Corumbaíba', 9),
                                                    ('Cristalina', 9),
                                                    ('Cristianópolis', 9),
                                                    ('Crixás', 9),
                                                    ('Cromínia', 9),
                                                    ('Cumari', 9),
                                                    ('Damianópolis', 9),
                                                    ('Damolândia', 9),
                                                    ('Davinópolis', 9),
                                                    ('Diorama', 9),
                                                    ('Divinópolis de Goiás', 9),
                                                    ('Doverlândia', 9),
                                                    ('Edealina', 9),
                                                    ('Edéia', 9),
                                                    ('Estrela do Norte', 9),
                                                    ('Faina', 9),
                                                    ('Fazenda Nova', 9),
                                                    ('Firminópolis', 9),
                                                    ('Flores de Goiás', 9),
                                                    ('Formosa', 9),
                                                    ('Formoso', 9),
                                                    ('Gameleira de Goiás', 9),
                                                    ('Goianápolis', 9),
                                                    ('Goiandira', 9),
                                                    ('Goianésia', 9),
                                                    ('Goiânia', 9),
                                                    ('Goianira', 9),
                                                    ('Goiás', 9),
                                                    ('Goiatuba', 9),
                                                    ('Gouvelândia', 9),
                                                    ('Guapó', 9),
                                                    ('Guaraíta', 9),
                                                    ('Guarani de Goiás', 9),
                                                    ('Guarinos', 9),
                                                    ('Heitoraí', 9),
                                                    ('Hidrolândia', 9),
                                                    ('Hidrolina', 9),
                                                    ('Iaciara', 9),
                                                    ('Inaciolândia', 9),
                                                    ('Indiara', 9),
                                                    ('Inhumas', 9),
                                                    ('Ipameri', 9),
                                                    ('Ipiranga de Goiás', 9),
                                                    ('Iporá', 9),
                                                    ('Israelândia', 9),
                                                    ('Itaberaí', 9),
                                                    ('Itaguari', 9),
                                                    ('Itaguaru', 9),
                                                    ('Itajá', 9),
                                                    ('Itapaci', 9),
                                                    ('Itapirapuã', 9),
                                                    ('Itapuranga', 9),
                                                    ('Itarumã', 9),
                                                    ('Itauçu', 9),
                                                    ('Itumbiara', 9),
                                                    ('Ivolândia', 9),
                                                    ('Jandaia', 9),
                                                    ('Jaraguá', 9),
                                                    ('Jataí', 9),
                                                    ('Jaupaci', 9),
                                                    ('Jesúpolis', 9),
                                                    ('Joviânia', 9),
                                                    ('Jussara', 9),
                                                    ('Lagoa Santa', 9),
                                                    ('Leopoldo de Bulhões', 9),
                                                    ('Luziânia', 9),
                                                    ('Mairipotaba', 9),
                                                    ('Mambaí', 9),
                                                    ('Mara Rosa', 9),
                                                    ('Marzagão', 9),
                                                    ('Matrinchã', 9),
                                                    ('Maurilândia', 9),
                                                    ('Mimoso de Goiás', 9),
                                                    ('Minaçu', 9),
                                                    ('Mineiros', 9),
                                                    ('Moiporá', 9),
                                                    ('Monte Alegre de Goiás', 9),
                                                    ('Montes Claros de Goiás', 9),
                                                    ('Montividiu', 9),
                                                    ('Montividiu do Norte', 9),
                                                    ('Morrinhos', 9),
                                                    ('Morro Agudo de Goiás', 9),
                                                    ('Mossâmedes', 9),
                                                    ('Mozarlândia', 9),
                                                    ('Mundo Novo', 9),
                                                    ('Mutunópolis', 9),
                                                    ('Nazário', 9),
                                                    ('Nerópolis', 9),
                                                    ('Niquelândia', 9),
                                                    ('Nova América', 9),
                                                    ('Nova Aurora', 9),
                                                    ('Nova Crixás', 9),
                                                    ('Nova Glória', 9),
                                                    ('Nova Iguaçu de Goiás', 9),
                                                    ('Nova Roma', 9),
                                                    ('Nova Veneza', 9),
                                                    ('Novo Brasil', 9),
                                                    ('Novo Gama', 9),
                                                    ('Novo Planalto', 9),
                                                    ('Orizona', 9),
                                                    ('Ouro Verde de Goiás', 9),
                                                    ('Ouvidor', 9),
                                                    ('Padre Bernardo', 9),
                                                    ('Palestina de Goiás', 9),
                                                    ('Palmeiras de Goiás', 9),
                                                    ('Palmelo', 9),
                                                    ('Palminópolis', 9),
                                                    ('Panamá', 9),
                                                    ('Paranaiguara', 9),
                                                    ('Paraúna', 9),
                                                    ('Perolândia', 9),
                                                    ('Petrolina de Goiás', 9),
                                                    ('Pilar de Goiás', 9),
                                                    ('Piracanjuba', 9),
                                                    ('Piranhas', 9),
                                                    ('Pirenópolis', 9),
                                                    ('Pires do Rio', 9),
                                                    ('Planaltina', 9),
                                                    ('Pontalina', 9),
                                                    ('Porangatu', 9),
                                                    ('Porteirão', 9),
                                                    ('Portelândia', 9),
                                                    ('Posse', 9),
                                                    ('Professor Jamil', 9),
                                                    ('Quirinópolis', 9),
                                                    ('Rialma', 9),
                                                    ('Rianápolis', 9),
                                                    ('Rio Quente', 9),
                                                    ('Rio Verde', 9),
                                                    ('Rubiataba', 9),
                                                    ('Sanclerlândia', 9),
                                                    ('Santa Bárbara de Goiás', 9),
                                                    ('Santa Cruz de Goiás', 9),
                                                    ('Santa Fé de Goiás', 9),
                                                    ('Santa Helena de Goiás', 9),
                                                    ('Santa Isabel', 9),
                                                    ('Santa Rita do Araguaia', 9),
                                                    ('Santa Rita do Novo Destino', 9),
                                                    ('Santa Rosa de Goiás', 9),
                                                    ('Santa Tereza de Goiás', 9),
                                                    ('Santa Terezinha de Goiás', 9),
                                                    ('Santo Antônio da Barra', 9),
                                                    ('Santo Antônio de Goiás', 9),
                                                    ('Santo Antônio do Descoberto', 9),
                                                    ('São Domingos', 9),
                                                    ('São Francisco de Goiás', 9),
                                                    ('São João d''Aliança', 9),
                                                    ('São João da Paraúna', 9),
                                                    ('São Luís de Montes Belos', 9),
                                                    ('São Luíz do Norte', 9),
                                                    ('São Miguel do Araguaia', 9),
                                                    ('São Miguel do Passa Quatro', 9),
                                                    ('São Patrício', 9),
                                                    ('São Simão', 9),
                                                    ('Senador Canedo', 9),
                                                    ('Serranópolis', 9),
                                                    ('Silvânia', 9),
                                                    ('Simolândia', 9),
                                                    ('Sítio d''Abadia', 9),
                                                    ('Taquaral de Goiás', 9),
                                                    ('Teresina de Goiás', 9),
                                                    ('Terezópolis de Goiás', 9),
                                                    ('Três Ranchos', 9),
                                                    ('Trindade', 9),
                                                    ('Trombas', 9),
                                                    ('Turvânia', 9),
                                                    ('Turvelândia', 9),
                                                    ('Uirapuru', 9),
                                                    ('Uruaçu', 9),
                                                    ('Uruana', 9),
                                                    ('Urutaí', 9),
                                                    ('Valparaíso de Goiás', 9),
                                                    ('Varjão', 9),
                                                    ('Vianópolis', 9),
                                                    ('Vicentinópolis', 9),
                                                    ('Vila Boa', 9),
                                                    ('Vila Propício', 9);
