Insert into cidade (nome_cidade, cidade_estado) values
('Acrelândia', 1),
('Assis Brasil', 1),
('Brasiléia', 1),
('Bujari', 1),
('Capixaba', 1),
('Cruzeiro do Sul', 1),
('Epitaciolândia', 1),
('Feijó', 1),
('Jordão', 1),
('Mâncio Lima', 1),
('Manoel Urbano', 1),
('Marechal Thaumaturgo', 1),
('Plácido de Castro', 1),
('Porto Walter', 1),
('Rio Branco', 1),
('Rodrigues Alves', 1),
('Santa Rosa do Purus', 1),
('Senador Guiomard', 1),
('Sena Madureira', 1),
('Tarauacá', 1),
('Xapuri', 1),
('Porto Acre', 1);