
Insert into cidade (nome_cidade, cidade_estado) values ('Alta Floresta D''Oeste', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Ariquemes', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Cabixi', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Cacoal', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Cerejeiras', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Colorado do Oeste', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Corumbiara', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Costa Marques', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Espigão D''Oeste', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Guajará-Mirim', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Jaru', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Ji-Paraná', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Machadinho D''Oeste', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Nova Brasilândia D''Oeste', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Ouro Preto do Oeste', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Pimenta Bueno', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Porto Velho', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Presidente Médici', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Rio Crespo', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Rolim de Moura', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Santa Luzia D''Oeste', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Vilhena', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('São Miguel do Guaporé', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Nova Mamoré', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Alvorada D''Oeste', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Alto Alegre dos Parecis', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Alto Paraíso', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Buritis', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Novo Horizonte do Oeste', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Cacaulândia', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Campo Novo de Rondônia', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Candeias do Jamari', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Castanheiras', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Chupinguaia', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Cujubim', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Governador Jorge Teixeira', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Itapuã do Oeste', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Ministro Andreazza', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Mirante da Serra', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Monte Negro', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Nova União', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Parecis', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Pimenteiras do Oeste', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Primavera de Rondônia', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('São Felipe D''Oeste', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('São Francisco do Guaporé', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Seringueiras', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Teixeirópolis', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Theobroma', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Urupá', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Vale do Anari', 22);
Insert into cidade (nome_cidade, cidade_estado) values ('Vale do Paraíso', 22);