INSERT INTO cidade (nome_cidade, cidade_estado) VALUES
                                                    ('Abatiá', 16),
                                                    ('Adrianópolis', 16),
                                                    ('Agudos do Sul', 16),
                                                    ('Almirante Tamandaré', 16),
                                                    ('Altamira do Paraná', 16),
                                                    ('Alto Paraíso', 16),
                                                    ('Alto Paraná', 16),
                                                    ('Alto Piquiri', 16),
                                                    ('Altônia', 16),
                                                    ('Alvorada do Sul', 16),
                                                    ('Amaporã', 16),
                                                    ('Ampére', 16),
                                                    ('Anahy', 16),
                                                    ('Andirá', 16),
                                                    ('Ângulo', 16),
                                                    ('Antonina', 16),
                                                    ('Antônio Olinto', 16),
                                                    ('Apucarana', 16),
                                                    ('Arapongas', 16),
                                                    ('Arapoti', 16),
                                                    ('Arapuã', 16),
                                                    ('Araruna', 16),
                                                    ('Araucária', 16),
                                                    ('Ariranha do Ivaí', 16),
                                                    ('Assaí', 16),
                                                    ('Assis Chateaubriand', 16),
                                                    ('Astorga', 16),
                                                    ('Atalaia', 16),
                                                    ('Balsa Nova', 16),
                                                    ('Bandeirantes', 16),
                                                    ('Barbosa Ferraz', 16),
                                                    ('Barra do Jacaré', 16),
                                                    ('Barracão', 16),
                                                    ('Bela Vista da Caroba', 16),
                                                    ('Bela Vista do Paraíso', 16),
                                                    ('Bituruna', 16),
                                                    ('Boa Esperança', 16),
                                                    ('Boa Esperança do Iguaçu', 16),
                                                    ('Boa Ventura de São Roque', 16),
                                                    ('Boa Vista da Aparecida', 16),
                                                    ('Bocaiúva do Sul', 16),
                                                    ('Bom Jesus do Sul', 16),
                                                    ('Bom Sucesso', 16),
                                                    ('Bom Sucesso do Sul', 16),
                                                    ('Borrazópolis', 16),
                                                    ('Braganey', 16),
                                                    ('Brasilândia do Sul', 16),
                                                    ('Cafeara', 16),
                                                    ('Cafelândia', 16),
                                                    ('Cafezal do Sul', 16),
                                                    ('Califórnia', 16),
                                                    ('Cambará', 16),
                                                    ('Cambé', 16),
                                                    ('Cambira', 16),
                                                    ('Campina da Lagoa', 16),
                                                    ('Campina do Simão', 16),
                                                    ('Campina Grande do Sul', 16),
                                                    ('Campo Bonito', 16),
                                                    ('Campo do Tenente', 16),
                                                    ('Campo Largo', 16),
                                                    ('Campo Magro', 16),
                                                    ('Campo Mourão', 16),
                                                    ('Cândido de Abreu', 16),
                                                    ('Candói', 16),
                                                    ('Cantagalo', 16),
                                                    ('Capanema', 16),
                                                    ('Capitão Leônidas Marques', 16),
                                                    ('Carambeí', 16),
                                                    ('Carlópolis', 16),
                                                    ('Cascavel', 16),
                                                    ('Castro', 16),
                                                    ('Catanduvas', 16),
                                                    ('Centenário do Sul', 16),
                                                    ('Cerro Azul', 16),
                                                    ('Céu Azul', 16),
                                                    ('Chopinzinho', 16),
                                                    ('Cianorte', 16),
                                                    ('Cidade Gaúcha', 16),
                                                    ('Clevelândia', 16),
                                                    ('Colombo', 16),
                                                    ('Colorado', 16),
                                                    ('Congonhinhas', 16),
                                                    ('Conselheiro Mairinck', 16),
                                                    ('Contenda', 16),
                                                    ('Corbélia', 16),
                                                    ('Cornélio Procópio', 16),
                                                    ('Coronel Domingos Soares', 16),
                                                    ('Coronel Vivida', 16),
                                                    ('Corumbataí do Sul', 16),
                                                    ('Cruz Machado', 16),
                                                    ('Cruzeiro do Iguaçu', 16),
                                                    ('Cruzeiro do Oeste', 16),
                                                    ('Cruzeiro do Sul', 16),
                                                    ('Cruzmaltina', 16),
                                                    ('Curitiba', 16),
                                                    ('Curiúva', 16),
                                                    ('Diamante d Oeste', 16),
('Diamante do Norte', 16),
('Diamante do Sul', 16),
('Dois Vizinhos', 16),
('Douradina', 16),
('Doutor Camargo', 16),
('Doutor Ulysses', 16),
('Enéas Marques', 16),
('Engenheiro Beltrão', 16),
('Entre Rios do Oeste', 16),
('Esperança Nova', 16),
('Espigão Alto do Iguaçu', 16),
('Farol', 16),
('Faxinal', 16),
('Fazenda Rio Grande', 16),
('Fênix', 16),
('Fernandes Pinheiro', 16),
('Figueira', 16),
('Flor da Serra do Sul', 16),
('Floraí', 16),
('Floresta', 16),
('Florestópolis', 16),
('Flórida', 16),
('Formosa do Oeste', 16),
('Foz do Iguaçu', 16),
('Foz do Jordão', 16),
('Francisco Alves', 16),
('Francisco Beltrão', 16),
('General Carneiro', 16),
('Godoy Moreira', 16),
('Goioerê', 16),
('Goioxim', 16),
('Grandes Rios', 16),
('Guaíra', 16),
('Guairaçá', 16),
('Guamiranga', 16),
('Guapirama', 16),
('Guaporema', 16),
('Guaraci', 16),
('Guaraniaçu', 16),
('Guarapuava', 16),
('Guaraqueçaba', 16),
('Guaratuba', 16),
('Honório Serpa', 16),
('Ibaiti', 16),
('Ibema', 16),
('Ibiporã', 16),
('Icaraíma', 16),
('Iguaraçu', 16),
('Iguatu', 16),
('Imbaú', 16),
('Imbituva', 16),
('Inácio Martins', 16),
('Inajá', 16),
('Indianópolis', 16),
('Ipiranga', 16),
('Iporã', 16),
('Iracema do Oeste', 16),
('Irati', 16),
('Iretama', 16),
('Itaguajé', 16),
('Itaipulândia', 16),
('Itambaracá', 16),
('Itambé', 16),
('Itapejara do Oeste', 16),
                                                    ('Itaperuçu', 16),
                                                    ('Itaúna do Sul', 16),
                                                    ('Ivaí', 16),
                                                    ('Ivaiporã', 16),
                                                    ('Ivaté', 16),
                                                    ('Ivatuba', 16),
                                                    ('Jaboti', 16),
                                                    ('Jacarezinho', 16),
                                                    ('Jaguapitã', 16),
                                                    ('Jaguariaíva', 16),
                                                    ('Jandaia do Sul', 16),
                                                    ('Janiópolis', 16),
                                                    ('Japira', 16),
                                                    ('Japurá', 16),
                                                    ('Jardim Alegre', 16),
                                                    ('Jardim Olinda', 16),
                                                    ('Jataizinho', 16),
                                                    ('Jesuítas', 16),
                                                    ('Joaquim Távora', 16),
                                                    ('Jundiaí do Sul', 16),
                                                    ('Juranda', 16),
                                                    ('Jussara', 16),
                                                    ('Kaloré', 16),
                                                    ('Lapa', 16),
                                                    ('Laranjal', 16),
                                                    ('Laranjeiras do Sul', 16),
                                                    ('Leópolis', 16),
                                                    ('Lidianópolis', 16),
                                                    ('Lindoeste', 16),
                                                    ('Loanda', 16),
                                                    ('Lobato', 16),
                                                    ('Londrina', 16),
                                                    ('Luiziana', 16),
                                                    ('Lunardelli', 16),
                                                    ('Lupionópolis', 16),
                                                    ('Mallet', 16),
                                                    ('Mamborê', 16),
                                                    ('Mandaguaçu', 16),
                                                    ('Mandaguari', 16),
                                                    ('Mandirituba', 16),
                                                    ('Manfrinópolis', 16),
                                                    ('Mangueirinha', 16),
                                                    ('Manoel Ribas', 16),
                                                    ('Marechal Cândido Rondon', 16),
                                                    ('Maria Helena', 16),
                                                    ('Marialva', 16),
                                                    ('Marilândia do Sul', 16),
                                                    ('Marilena', 16),
                                                    ('Mariluz', 16),
                                                    ('Maringá', 16),
                                                    ('Mariópolis', 16),
                                                    ('Maripá', 16),
                                                    ('Marmeleiro', 16),
                                                    ('Marquinho', 16),
                                                    ('Marumbi', 16),
                                                    ('Matelândia', 16),
                                                    ('Matinhos', 16),
                                                    ('Mato Rico', 16),
                                                    ('Mauá da Serra', 16),
                                                    ('Medianeira', 16),
                                                    ('Mercedes', 16),
                                                    ('Mirador', 16),
                                                    ('Miraselva', 16),
                                                    ('Missal', 16),
                                                    ('Moreira Sales', 16),
                                                    ('Morretes', 16),
                                                    ('Munhoz de Melo', 16),
                                                    ('Nossa Senhora das Graças', 16),
                                                    ('Nova Aliança do Ivaí', 16),
                                                    ('Nova América da Colina', 16),
                                                    ('Nova Aurora', 16),
                                                    ('Nova Cantu', 16),
                                                    ('Nova Esperança', 16),
                                                    ('Nova Esperança do Sudoeste', 16),
                                                    ('Nova Fátima', 16),
                                                    ('Nova Laranjeiras', 16),
                                                    ('Nova Londrina', 16),
                                                    ('Nova Olímpia', 16),
                                                    ('Nova Prata do Iguaçu', 16),
                                                    ('Nova Santa Bárbara', 16),
                                                    ('Nova Santa Rosa', 16),
                                                    ('Nova Tebas', 16),
                                                    ('Novo Itacolomi', 16),
                                                    ('Ortigueira', 16),
                                                    ('Ourizona', 16),
                                                    ('Ouro Verde do Oeste', 16),
                                                    ('Paiçandu', 16),
                                                    ('Palmas', 16),
                                                    ('Palmeira', 16),
                                                    ('Palmital', 16),
                                                    ('Palotina', 16),
                                                    ('Paraíso do Norte', 16),
                                                    ('Paranacity', 16),
                                                    ('Paranaguá', 16),
                                                    ('Paranapoema', 16),
                                                    ('Paranavaí', 16),
                                                    ('Pato Bragado', 16),
                                                    ('Pato Branco', 16),
                                                    ('Paula Freitas', 16),
                                                    ('Paulo Frontin', 16),
                                                    ('Peabiru', 16),
                                                    ('Perobal', 16),
                                                    ('Pérola', 16),
                                                    ('Pérola do Oeste', 16),
('Piên', 16),
('Pinhais', 16),
('Pinhal de São Bento', 16),
('Pinhalão', 16),
('Pinhão', 16),
('Piraí do Sul', 16),
('Piraquara', 16),
('Pitanga', 16),
('Pitangueiras', 16),
('Planaltina do Paraná', 16),
('Planalto', 16),
('Ponta Grossa', 16),
('Pontal do Paraná', 16),
('Porecatu', 16),
('Porto Amazonas', 16),
('Porto Barreiro', 16),
('Porto Rico', 16),
('Porto Vitória', 16),
('Prado Ferreira', 16),
('Pranchita', 16),
('Presidente Castelo Branco', 16),
('Primeiro de Maio', 16),
('Prudentópolis', 16),
('Quarto Centenário', 16),
('Quatiguá', 16),
('Quatro Barras', 16),
('Quatro Pontes', 16),
('Quedas do Iguaçu', 16),
('Querência do Norte', 16),
('Quinta do Sol', 16),
('Quitandinha', 16),
('Ramilândia', 16),
('Rancho Alegre', 16),
('Rancho Alegre do Oeste', 16),
                                                    ('Realeza', 16),
                                                    ('Rebouças', 16),
                                                    ('Renascença', 16),
                                                    ('Reserva', 16),
                                                    ('Reserva do Iguaçu', 16),
                                                    ('Ribeirão Claro', 16),
                                                    ('Ribeirão do Pinhal', 16),
                                                    ('Rio Azul', 16),
                                                    ('Rio Bom', 16),
                                                    ('Rio Bonito do Iguaçu', 16),
                                                    ('Rio Branco do Ivaí', 16),
                                                    ('Rio Branco do Sul', 16),
                                                    ('Rio Negro', 16),
                                                    ('Rolândia', 16),
                                                    ('Roncador', 16),
                                                    ('Rondon', 16),
                                                    ('Rosário do Ivaí', 16),
                                                    ('Sabáudia', 16),
                                                    ('Salgado Filho', 16),
                                                    ('Salto do Itararé', 16),
                                                    ('Salto do Lontra', 16),
                                                    ('Santa Amélia', 16),
                                                    ('Santa Cecília do Pavão', 16),
                                                    ('Santa Cruz de Monte Castelo', 16),
                                                    ('Santa Fé', 16),
                                                    ('Santa Helena', 16),
                                                    ('Santa Inês', 16),
                                                    ('Santa Isabel do Ivaí', 16),
                                                    ('Santa Izabel do Oeste', 16),
                                                    ('Santa Lúcia', 16),
                                                    ('Santa Maria do Oeste', 16),
                                                    ('Santa Mariana', 16),
                                                    ('Santa Mônica', 16),
                                                    ('Santa Tereza do Oeste', 16),
                                                    ('Santa Terezinha de Itaipu', 16),
                                                    ('Santana do Itararé', 16),
                                                    ('Santo Antônio da Platina', 16),
                                                    ('Santo Antônio do Caiuá', 16),
                                                    ('Santo Antônio do Paraíso', 16),
                                                    ('Santo Antônio do Sudoeste', 16),
                                                    ('Santo Inácio', 16),
                                                    ('São Carlos do Ivaí', 16),
                                                    ('São Jerônimo da Serra', 16),
                                                    ('São João', 16),
                                                    ('São João do Caiuá', 16),
                                                    ('São João do Ivaí', 16),
                                                    ('São João do Triunfo', 16),
                                                    ('São Jorge do Oeste', 16),
('São Jorge do Ivaí', 16),
('São Jorge do Patrocínio', 16),
('São José da Boa Vista', 16),
('São José das Palmeiras', 16),
('São José dos Pinhais', 16),
('São Manoel do Paraná', 16),
('São Mateus do Sul', 16),
('São Miguel do Iguaçu', 16),
('São Pedro do Iguaçu', 16),
('São Pedro do Ivaí', 16),
('São Pedro do Paraná', 16),
('São Sebastião da Amoreira', 16),
('São Tomé', 16),
('Sapopema', 16),
('Sarandi', 16),
('Saudade do Iguaçu', 16),
('Sengés', 16),
('Serranópolis do Iguaçu', 16),
('Sertaneja', 16),
('Sertanópolis', 16),
('Siqueira Campos', 16),
('Sulina', 16),
('Tamarana', 16),
('Tamboara', 16),
('Tapejara', 16),
('Tapira', 16),
('Teixeira Soares', 16),
('Telêmaco Borba', 16),
('Terra Boa', 16),
('Terra Rica', 16),
('Terra Roxa', 16),
('Tibagi', 16),
('Tijucas do Sul', 16),
('Toledo', 16),
('Tomazina', 16),
('Três Barras do Paraná', 16),
('Tunas do Paraná', 16),
('Tuneiras do Oeste', 16),
('Tupãssi', 16),
('Turvo', 16),
('Ubiratã', 16),
('Umuarama', 16),
('União da Vitória', 16),
('Uniflor', 16),
('Uraí', 16),
('Ventania', 16),
('Vera Cruz do Oeste', 16),
('Verê', 16),
('Virmond', 16),
('Vitorino', 16),
('Wenceslau Braz', 16),
('Xambrê', 16);
