INSERT INTO cidade (nome_cidade, cidade_estado)
VALUES
    ('Água Branca', 15),
    ('Aguiar', 15),
    ('Alagoa Grande', 15),
    ('Alagoa Nova', 15),
    ('Alagoinha', 15),
    ('Alcantil', 15),
    ('Algodão de Jandaíra', 15),
    ('Alhandra', 15),
    ('Amparo', 15),
    ('Aparecida', 15),
    ('Araçagi', 15),
    ('Arara', 15),
    ('Araruna', 15),
    ('Areia', 15),
    ('Areia de Baraúnas', 15),
    ('Areial', 15),
    ('Aroeiras', 15),
    ('Assunção', 15),
    ('Baía da Traição', 15),
    ('Bananeiras', 15),
    ('Baraúna', 15),
    ('Barra de Santa Rosa', 15),
    ('Barra de Santana', 15),
    ('Barra de São Miguel', 15),
    ('Bayeux', 15),
    ('Belém', 15),
    ('Belém do Brejo do Cruz', 15),
    ('Bernardino Batista', 15),
    ('Boa Ventura', 15),
    ('Boa Vista', 15),
    ('Bom Jesus', 15),
    ('Bom Sucesso', 15),
    ('Bonito de Santa Fé', 15),
    ('Boqueirão', 15),
    ('Borborema', 15),
    ('Brejo do Cruz', 15),
    ('Brejo dos Santos', 15),
    ('Caaporã', 15),
    ('Cabaceiras', 15),
    ('Cabedelo', 15),
    ('Cachoeira dos Índios', 15),
    ('Cacimba de Areia', 15),
    ('Cacimba de Dentro', 15),
    ('Cacimbas', 15),
    ('Caiçara', 15),
    ('Cajazeiras', 15),
    ('Cajazeirinhas', 15),
    ('Caldas Brandão', 15),
    ('Camalaú', 15),
    ('Campina Grande', 15),
    ('Campo de Santana', 15),
    ('Capim', 15),
    ('Caraúbas', 15),
    ('Carrapateira', 15),
    ('Casserengue', 15),
    ('Catingueira', 15),
    ('Catolé do Rocha', 15),
    ('Caturité', 15),
    ('Conceição', 15),
    ('Condado', 15),
    ('Conde', 15),
    ('Congo', 15),
    ('Coremas', 15),
    ('Coxixola', 15),
    ('Cruz do Espírito Santo', 15),
    ('Cubati', 15),
    ('Cuité', 15),
    ('Cuité de Mamanguape', 15),
    ('Cuitegi', 15),
    ('Curral de Cima', 15),
    ('Curral Velho', 15),
    ('Damião', 15),
    ('Desterro', 15),
    ('Diamante', 15),
    ('Dona Inês', 15),
    ('Duas Estradas', 15),
    ('Emas', 15),
    ('Esperança', 15),
    ('Fagundes', 15),
    ('Frei Martinho', 15),
    ('Gado Bravo', 15),
    ('Guarabira', 15),
    ('Gurinhém', 15),
    ('Gurjão', 15),
    ('Ibiara', 15),
    ('Igaracy', 15),
    ('Imaculada', 15),
    ('Ingá', 15),
    ('Itabaiana', 15),
    ('Itaporanga', 15),
    ('Itapororoca', 15),
    ('Itatuba', 15),
    ('Jacaraú', 15),
    ('Jericó', 15),
    ('João Pessoa', 15),
    ('Juarez Távora', 15),
    ('Juazeirinho', 15),
    ('Junco do Seridó', 15),
    ('Juripiranga', 15),
    ('Juru', 15),
    ('Lagoa', 15),
    ('Lagoa de Dentro', 15),
    ('Lagoa Seca', 15),
    ('Lastro', 15),
    ('Livramento', 15),
    ('Logradouro', 15),
    ('Lucena', 15),
    ('Mãe d`Água', 15),
    ('Malta', 15),
    ('Mamanguape', 15),
    ('Manaíra', 15),
    ('Marcação', 15),
    ('Mari', 15),
    ('Marizópolis', 15),
    ('Massaranduba', 15),
    ('Mataraca', 15),
    ('Matinhas', 15),
    ('Mato Grosso', 15),
    ('Maturéia', 15),
    ('Mogeiro', 15),
    ('Montadas', 15),
    ('Monte Horebe', 15),
    ('Monteiro', 15),
    ('Mulungu', 15),
    ('Natuba', 15),
    ('Nazarezinho', 15),
    ('Nova Floresta', 15),
    ('Nova Olinda', 15),
    ('Nova Palmeira', 15),
    ('Olho d`Água', 15),
    ('Olivedos', 15),
    ('Ouro Velho', 15),
    ('Parari', 15),
    ('Passagem', 15),
    ('Patos', 15),
    ('Paulista', 15),
    ('Pedra Branca', 15),
    ('Pedra Lavrada', 15),
    ('Pedras de Fogo', 15),
    ('Pedro Régis', 15),
    ('Piancó', 15),
    ('Picuí', 15),
    ('Pilar', 15),
    ('Pilões', 15),
    ('Pilõezinhos', 15),
    ('Pirpirituba', 15),
    ('Pitimbu', 15),
    ('Pocinhos', 15),
    ('Poço Dantas', 15),
    ('Poço de José de Moura', 15),
    ('Pombal', 15),
    ('Prata', 15),
    ('Princesa Isabel', 15),
    ('Puxinanã', 15),
    ('Queimadas', 15),
    ('Quixabá', 15),
    ('Remígio', 15),
    ('Riachão', 15),
    ('Riachão do Bacamarte', 15),
    ('Riachão do Poço', 15),
    ('Riacho de Santo Antônio', 15),
    ('Riacho dos Cavalos', 15),
    ('Rio Tinto', 15),
    ('Salgadinho', 15),
    ('Salgado de São Félix', 15),
    ('Santa Cecília', 15),
    ('Santa Cruz', 15),
    ('Santa Helena', 15),
    ('Santa Inês', 15),
    ('Santa Luzia', 15),
    ('Santa Rita', 15),
    ('Santa Teresinha', 15),
    ('Santana de Mangueira', 15),
    ('Santana dos Garrotes', 15),
    ('Santarém', 15),
    ('Santo André', 15),
    ('São Bentinho', 15),
    ('São Bento', 15),
    ('São Domingos', 15),
    ('São Domingos do Cariri', 15),
    ('São Francisco', 15),
    ('São João do Cariri', 15),
    ('São João do Rio do Peixe', 15),
    ('São João do Tigre', 15),
    ('São José da Lagoa Tapada', 15),
    ('São José de Caiana', 15),
    ('São José de Espinharas', 15),
    ('São José de Piranhas', 15),
    ('São José de Princesa', 15),
    ('São José do Bonfim', 15),
    ('São José do Brejo do Cruz', 15),
    ('São José do Sabugi', 15),
    ('São José dos Cordeiros', 15),
    ('São José dos Ramos', 15),
    ('São Mamede', 15),
    ('São Miguel de Taipu', 15),
    ('São Sebastião de Lagoa de Roça', 15),
    ('São Sebastião do Umbuzeiro', 15),
    ('Sapé', 15),
    ('Seridó', 15),
    ('Serra Branca', 15),
    ('Serra da Raiz', 15),
    ('Serra Grande', 15),
    ('Serra Redonda', 15),
    ('Serraria', 15),
    ('Sertãozinho', 15),
    ('Sobrado', 15),
    ('Solânea', 15),
    ('Soledade', 15),
    ('Sossêgo', 15),
    ('Sousa', 15),
    ('Sumé', 15),
    ('Taperoá', 15),
    ('Tavares', 15),
    ('Teixeira', 15),
    ('Tenório', 15),
    ('Triunfo', 15),
    ('Uiraúna', 15),
    ('Umbuzeiro', 15),
    ('Várzea', 15),
    ('Vieirópolis', 15),
    ('Vista Serrana', 15),
    ('Zabelê', 15);