INSERT INTO cidade (nome_cidade, cidade_estado) VALUES
                                                    ('Acorizal', 11),
                                                    ('Água Boa', 11),
                                                    ('Alta Floresta', 11),
                                                    ('Alto Araguaia', 11),
                                                    ('Alto Boa Vista', 11),
                                                    ('Alto Garças', 11),
                                                    ('Alto Paraguai', 11),
                                                    ('Alto Taquari', 11),
                                                    ('Apiacás', 11),
                                                    ('Araguaiana', 11),
                                                    ('Araguainha', 11),
                                                    ('Araputanga', 11),
                                                    ('Arenápolis', 11),
                                                    ('Aripuanã', 11),
                                                    ('Barão de Melgaço', 11),
                                                    ('Barra do Bugres', 11),
                                                    ('Barra do Garças', 11),
                                                    ('Bom Jesus do Araguaia', 11),
                                                    ('Brasnorte', 11),
                                                    ('Cáceres', 11),
                                                    ('Campinápolis', 11),
                                                    ('Campo Novo do Parecis', 11),
                                                    ('Campo Verde', 11),
                                                    ('Campos de Júlio', 11),
                                                    ('Canabrava do Norte', 11),
                                                    ('Canarana', 11),
                                                    ('Carlinda', 11),
                                                    ('Castanheira', 11),
                                                    ('Chapada dos Guimarães', 11),
                                                    ('Cláudia', 11),
                                                    ('Cocalinho', 11),
                                                    ('Colíder', 11),
                                                    ('Colniza', 11),
                                                    ('Comodoro', 11),
                                                    ('Confresa', 11),
                                                    ('Conquista d''Oeste', 11),
                                                    ('Cotriguaçu', 11),
                                                    ('Curvelândia', 11),
                                                    ('Cuiabá', 11),
                                                    ('Denise', 11),
                                                    ('Diamantino', 11),
                                                    ('Dom Aquino', 11),
                                                    ('Feliz Natal', 11),
                                                    ('Figueirópolis d''Oeste', 11),
                                                    ('Gaúcha do Norte', 11),
                                                    ('General Carneiro', 11),
                                                    ('Glória d''Oeste', 11),
                                                    ('Guarantã do Norte', 11),
                                                    ('Guiratinga', 11),
                                                    ('Indiavaí', 11),
                                                    ('Ipiranga do Norte', 11),
                                                    ('Itanhangá', 11),
                                                    ('Itaúba', 11),
                                                    ('Itiquira', 11),
                                                    ('Jaciara', 11),
                                                    ('Jangada', 11),
                                                    ('Jauru', 11),
                                                    ('Juara', 11),
                                                    ('Juína', 11),
                                                    ('Juruena', 11),
                                                    ('Juscimeira', 11),
                                                    ('Lambari d''Oeste', 11),
                                                    ('Lucas do Rio Verde', 11),
                                                    ('Luciara', 11),
                                                    ('Marcelândia', 11),
                                                    ('Matupá', 11),
                                                    ('Mirassol d''Oeste', 11),
                                                    ('Nobres', 11),
                                                    ('Nortelândia', 11),
                                                    ('Nossa Senhora do Livramento', 11),
                                                    ('Nova Bandeirantes', 11),
                                                    ('Nova Brasilândia', 11),
                                                    ('Nova Canaã do Norte', 11),
                                                    ('Nova Guarita', 11),
                                                    ('Nova Lacerda', 11),
                                                    ('Nova Marilândia', 11),
                                                    ('Nova Maringá', 11),
                                                    ('Nova Monte Verde', 11),
                                                    ('Nova Mutum', 11),
                                                    ('Nova Nazaré', 11),
                                                    ('Nova Olímpia', 11),
                                                    ('Nova Santa Helena', 11),
                                                    ('Nova Ubiratã', 11),
                                                    ('Nova Xavantina', 11),
                                                    ('Novo Horizonte do Norte', 11),
                                                    ('Novo Mundo', 11),
                                                    ('Novo Santo Antônio', 11),
                                                    ('Novo São Joaquim', 11),
                                                    ('Paranaíta', 11),
                                                    ('Paranatinga', 11),
                                                    ('Pedra Preta', 11),
                                                    ('Peixoto de Azevedo', 11),
                                                    ('Planalto da Serra', 11),
                                                    ('Poconé', 11),
                                                    ('Pontal do Araguaia', 11),
                                                    ('Ponte Branca', 11),
                                                    ('Pontes e Lacerda', 11),
                                                    ('Porto Alegre do Norte', 11),
                                                    ('Porto dos Gaúchos', 11),
                                                    ('Porto Esperidião', 11),
                                                    ('Porto Estrela', 11),
                                                    ('Poxoréo', 11),
                                                    ('Primavera do Leste', 11),
                                                    ('Querência', 11),
                                                    ('Reserva do Cabaçal', 11),
                                                    ('Ribeirão Cascalheira', 11),
                                                    ('Ribeirãozinho', 11),
                                                    ('Rio Branco', 11),
                                                    ('Rondolândia', 11),
                                                    ('Rondonópolis', 11),
                                                    ('Rosário Oeste', 11),
                                                    ('Salto do Céu', 11),
                                                    ('Santa Carmem', 11),
                                                    ('Santa Cruz do Xingu', 11),
                                                    ('Santa Rita do Trivelato', 11),
                                                    ('Santa Terezinha', 11),
                                                    ('Santo Afonso', 11),
                                                    ('Santo Antônio do Leste', 11),
                                                    ('Santo Antônio do Leverger', 11),
                                                    ('São Félix do Araguaia', 11),
                                                    ('São José do Povo', 11),
                                                    ('São José do Rio Claro', 11),
                                                    ('São José do Xingu', 11),
                                                    ('São José dos Quatro Marcos', 11),
                                                    ('São Pedro da Cipa', 11),
                                                    ('Sapezal', 11),
                                                    ('Serra Nova Dourada', 11),
                                                    ('Sinop', 11),
                                                    ('Sorriso', 11),
                                                    ('Tabaporã', 11),
                                                    ('Tangará da Serra', 11),
                                                    ('Tapurah', 11),
                                                    ('Terra Nova do Norte', 11),
                                                    ('Tesouro', 11),
                                                    ('Torixoréu', 11),
                                                    ('União do Sul', 11),
                                                    ('Vale de São Domingos', 11),
                                                    ('Várzea Grande', 11),
                                                    ('Vera', 11),
                                                    ('Vila Bela da Santíssima Trindade', 11),
                                                    ('Vila Rica', 11);
