INSERT INTO cidade (nome_cidade, cidade_estado)
VALUES
    ('Acauã', 18),
    ('Agricolândia', 18),
    ('Água Branca', 18),
    ('Alagoinha do Piauí', 18),
    ('Alegrete do Piauí', 18),
    ('Alto Longá', 18),
    ('Altos', 18),
    ('Alvorada do Gurguéia', 18),
    ('Amarante', 18),
    ('Angical do Piauí', 18),
    ('Anísio de Abreu', 18),
    ('Antônio Almeida', 18),
    ('Aroazes', 18),
    ('Aroeiras do Itaim', 18),
    ('Arraial', 18),
    ('Assunção do Piauí', 18),
    ('Avelino Lopes', 18),
    ('Baixa Grande do Ribeiro', 18),
    ('Barra d`Alcântara', 18),
    ('Barras', 18),
    ('Barreiras do Piauí', 18),
    ('Barro Duro', 18),
    ('Batalha', 18),
    ('Bela Vista do Piauí', 18),
    ('Belém do Piauí', 18),
    ('Beneditinos', 18),
    ('Bertolínia', 18),
    ('Betânia do Piauí', 18),
    ('Boa Hora', 18),
    ('Bocaina', 18),
    ('Bom Jesus', 18),
    ('Bom Princípio do Piauí', 18),
    ('Bonfim do Piauí', 18),
    ('Boqueirão do Piauí', 18),
    ('Brasileira', 18),
    ('Brejo do Piauí', 18),
    ('Buriti dos Lopes', 18),
    ('Buriti dos Montes', 18),
    ('Cabeceiras do Piauí', 18),
    ('Cajazeiras do Piauí', 18),
    ('Cajueiro da Praia', 18),
    ('Caldeirão Grande do Piauí', 18),
    ('Campinas do Sul', 18),
    ('Campo Alegre do Fidalgo', 18),
    ('Campo Grande do Piauí', 18),
    ('Campo Largo do Piauí', 18),
    ('Campo Maior', 18),
    ('Canavieira', 18),
    ('Canto do Buriti', 18),
    ('Capitão de Campos', 18),
    ('Capitão Gervásio Oliveira', 18),
    ('Caracol', 18),
    ('Caraúbas do Piauí', 18),
    ('Caridade do Piauí', 18),
    ('Castelo do Piauí', 18),
    ('Caxingó', 18),
    ('Cocal', 18),
    ('Cocal de Telha', 18),
    ('Cocal dos Alves', 18),
    ('Coivaras', 18),
    ('Colônia do Gurguéia', 18),
    ('Colônia do Piauí', 18),
    ('Conceição do Canindé', 18),
    ('Coronel José Dias', 18),
    ('Corrente', 18),
    ('Cristalândia do Piauí', 18),
    ('Cristino Castro', 18),
    ('Curimatá', 18),
    ('Currais', 18),
    ('Curral Novo do Piauí', 18),
    ('Curralinhos', 18),
    ('Demerval Lobão', 18),
    ('Dirceu Arcoverde', 18),
    ('Dom Expedito Lopes', 18),
    ('Dom Inocêncio', 18),
    ('Domingos Mourão', 18),
    ('Elesbão Veloso', 18),
    ('Eliseu Martins', 18),
    ('Esperantina', 18),
    ('Fartura do Piauí', 18),
    ('Flores do Piauí', 18),
    ('Floresta do Piauí', 18),
    ('Floriano', 18),
    ('Francinópolis', 18),
    ('Francisco Ayres', 18),
    ('Francisco Macedo', 18),
    ('Francisco Santos', 18),
    ('Fronteiras', 18),
    ('Geminiano', 18),
    ('Gilbués', 18),
    ('Guadalupe', 18),
    ('Guaribas', 18),
    ('Hugo Napoleão', 18),
    ('Ilha Grande', 18),
    ('Inhuma', 18),
    ('Ipiranga do Piauí', 18),
    ('Isaías Coelho', 18),
    ('Itainópolis', 18),
    ('Itaueira', 18),
    ('Jacobina do Piauí', 18),
    ('Jaicós', 18),
    ('Jardim do Mulato', 18),
    ('Jatobá do Piauí', 18),
    ('Jerumenha', 18),
    ('João Costa', 18),
    ('Joaquim Pires', 18),
    ('Joca Marques', 18),
    ('José de Freitas', 18),
    ('Juazeiro do Piauí', 18),
    ('Júlio Borges', 18),
    ('Jurema', 18),
    ('Lagoa Alegre', 18),
    ('Lagoa de São Francisco', 18),
    ('Lagoa do Barro do Piauí', 18),
    ('Lagoa do Piauí', 18),
    ('Lagoa do Sítio', 18),
    ('Lagoinha do Piauí', 18),
    ('Landri Sales', 18),
    ('Luís Correia', 18),
    ('Luzilândia', 18),
    ('Madeiro', 18),
    ('Manoel Emídio', 18),
    ('Marcolândia', 18),
    ('Marcos Parente', 18),
    ('Massapê do Piauí', 18),
    ('Matias Olímpio', 18),
    ('Miguel Alves', 18),
    ('Miguel Leão', 18),
    ('Milton Brandão', 18),
    ('Monsenhor Gil', 18),
    ('Monsenhor Hipólito', 18),
    ('Monte Alegre do Piauí', 18),
    ('Morro Cabeça no Tempo', 18),
    ('Morro do Chapéu do Piauí', 18),
    ('Murici dos Portelas', 18),
    ('Nazaré do Piauí', 18),
    ('Nazária', 18),
    ('Nossa Senhora de Nazaré', 18),
    ('Nossa Senhora dos Remédios', 18),
    ('Nova Santa Rita', 18),
    ('Novo Oriente do Piauí', 18),
    ('Novo Santo Antônio', 18),
    ('Oeiras', 18),
    ('Olho d`Água do Piauí', 18),
    ('Padre Marcos', 18),
    ('Paes Landim', 18),
    ('Pajeú do Piauí', 18),
    ('Palmeira do Piauí', 18),
    ('Palmeirais', 18),
    ('Paquetá', 18),
    ('Parnaguá', 18),
    ('Parnaíba', 18),
    ('Passagem Franca do Piauí', 18),
    ('Patos do Piauí', 18),
    ('Pau d`Arco do Piauí', 18),
    ('Paulistana', 18),
    ('Pavussu', 18),
    ('Pedro II', 18),
    ('Pedro Laurentino', 18),
    ('Picos', 18),
    ('Pimenteiras', 18),
    ('Pio IX', 18),
    ('Piracuruca', 18),
    ('Piripiri', 18),
    ('Porto', 18),
    ('Porto Alegre do Piauí', 18),
    ('Prata do Piauí', 18),
    ('Queimada Nova', 18),
    ('Redenção do Gurguéia', 18),
    ('Regeneração', 18),
    ('Riacho Frio', 18),
    ('Ribeira do Piauí', 18),
    ('Ribeiro Gonçalves', 18),
    ('Rio Grande do Piauí', 18),
    ('Santa Cruz do Piauí', 18),
    ('Santa Cruz dos Milagres', 18),
    ('Santa Filomena', 18),
    ('Santa Luz', 18),
    ('Santa Rosa do Piauí', 18),
    ('Santana do Piauí', 18),
    ('Santo Antônio de Lisboa', 18),
    ('Santo Antônio dos Milagres', 18),
    ('Santo Inácio do Piauí', 18),
    ('São Braz do Piauí', 18),
    ('São Félix do Piauí', 18),
    ('São Francisco de Assis do Piauí', 18),
    ('São Francisco do Piauí', 18),
    ('São Gonçalo do Gurguéia', 18),
    ('São Gonçalo do Piauí', 18),
    ('São João da Canabrava', 18),
    ('São João da Fronteira', 18),
    ('São João da Serra', 18),
    ('São João da Varjota', 18),
    ('São João do Arraial', 18),
    ('São João do Piauí', 18),
    ('São José do Divino', 18),
    ('São José do Peixe', 18),
    ('São José do Piauí', 18),
    ('São Julião', 18),
    ('São Lourenço do Piauí', 18),
    ('São Luis do Piauí', 18),
    ('São Miguel da Baixa Grande', 18),
    ('São Miguel do Fidalgo', 18),
    ('São Miguel do Tapuio', 18),
    ('São Pedro do Piauí', 18),
    ('São Raimundo Nonato', 18),
    ('Sebastião Barros', 18),
    ('Sebastião Leal', 18),
    ('Sigefredo Pacheco', 18),
    ('Simões', 18),
    ('Simplício Mendes', 18),
    ('Socorro do Piauí', 18),
    ('Sussuapara', 18),
    ('Tamboril do Piauí', 18),
    ('Tanque do Piauí', 18),
    ('Teresina', 18),
    ('União', 18),
    ('Uruçuí', 18),
    ('Valença do Piauí', 18),
    ('Várzea Branca', 18),
    ('Várzea Grande', 18),
    ('Vera Mendes', 18),
    ('Vila Nova do Piauí', 18),
    ('Wall Ferraz', 18);