INSERT INTO cidade (nome_cidade, cidade_estado)
VALUES
    ('Angra dos Reis', 19),
    ('Aperibé', 19),
    ('Araruama', 19),
    ('Areal', 19),
    ('Armação dos Búzios', 19),
    ('Arraial do Cabo', 19),
    ('Barra do Piraí', 19),
    ('Barra Mansa', 19),
    ('Belford Roxo', 19),
    ('Bom Jardim', 19),
    ('Bom Jesus do Itabapoana', 19),
    ('Cabo Frio', 19),
    ('Cachoeiras de Macacu', 19),
    ('Cambuci', 19),
    ('Campos dos Goytacazes', 19),
    ('Cantagalo', 19),
    ('Carapebus', 19),
    ('Cardoso Moreira', 19),
    ('Carmo', 19),
    ('Casimiro de Abreu', 19),
    ('Comendador Levy Gasparian', 19),
    ('Conceição de Macabu', 19),
    ('Cordeiro', 19),
    ('Duas Barras', 19),
    ('Duque de Caxias', 19),
    ('Engenheiro Paulo de Frontin', 19),
    ('Guapimirim', 19),
    ('Iguaba Grande', 19),
    ('Itaboraí', 19),
    ('Itaguaí', 19),
    ('Italva', 19),
    ('Itaocara', 19),
    ('Itaperuna', 19),
    ('Itatiaia', 19),
    ('Japeri', 19),
    ('Laje do Muriaé', 19),
    ('Macaé', 19),
    ('Macuco', 19),
    ('Magé', 19),
    ('Mangaratiba', 19),
    ('Maricá', 19),
    ('Mendes', 19),
    ('Mesquita', 19),
    ('Miguel Pereira', 19),
    ('Miracema', 19),
    ('Natividade', 19),
    ('Nilópolis', 19),
    ('Niterói', 19),
    ('Nova Friburgo', 19),
    ('Nova Iguaçu', 19),
    ('Paracambi', 19),
    ('Paraíba do Sul', 19),
    ('Paraty', 19),
    ('Paty do Alferes', 19),
    ('Petrópolis', 19),
    ('Pinheiral', 19),
    ('Piraí', 19),
    ('Porciúncula', 19),
    ('Porto Real', 19),
    ('Quatis', 19),
    ('Queimados', 19),
    ('Quissamã', 19),
    ('Resende', 19),
    ('Rio Bonito', 19),
    ('Rio Claro', 19),
    ('Rio das Flores', 19),
    ('Rio das Ostras', 19),
    ('Rio de Janeiro', 19),
    ('Santa Maria Madalena', 19),
    ('Santo Antônio de Pádua', 19),
    ('São Fidélis', 19),
    ('São Francisco de Itabapoana', 19),
    ('São Gonçalo', 19),
    ('São João da Barra', 19),
    ('São João de Meriti', 19),
    ('São José de Ubá', 19),
    ('São José do Vale do Rio Preto', 19),
    ('São Pedro da Aldeia', 19),
    ('São Sebastião do Alto', 19),
    ('Sapucaia', 19),
    ('Saquarema', 19),
    ('Seropédica', 19),
    ('Silva Jardim', 19),
    ('Sumidouro', 19),
    ('Tanguá', 19),
    ('Teresópolis', 19),
    ('Trajano de Moraes', 19),
    ('Três Rios', 19),
    ('Valença', 19),
    ('Varre-Sai', 19),
    ('Vassouras', 19),
    ('Volta Redonda', 19);
