INSERT INTO cidade (nome_cidade, cidade_estado)
VALUES
    ('Açailândia', 10),
    ('Afonso Cunha', 10),
    ('Água Doce do Maranhão', 10),
    ('Alcântara', 10),
    ('Aldeias Altas', 10),
    ('Altamira do Maranhão', 10),
    ('Alto Alegre do Maranhão', 10),
    ('Alto Alegre do Pindaré', 10),
    ('Alto Parnaíba', 10),
    ('Amapá do Maranhão', 10),
    ('Amarante do Maranhão', 10),
    ('Anajatuba', 10),
    ('Anapurus', 10),
    ('Apicum-Açu', 10),
    ('Araguanã', 10),
    ('Araioses', 10),
    ('Arame', 10),
    ('Arari', 10),
    ('Axixá', 10),
    ('Bacabal', 10),
    ('Bacabeira', 10),
    ('Bacuri', 10),
    ('Bacurituba', 10),
    ('Balsas', 10),
    ('Barão de Grajaú', 10),
    ('Barra do Corda', 10),
    ('Barreirinhas', 10),
    ('Bela Vista do Maranhão', 10),
    ('Belágua', 10),
    ('Benedito Leite', 10),
    ('Bequimão', 10),
    ('Bernardo do Mearim', 10),
    ('Boa Vista do Gurupi', 10),
    ('Bom Jardim', 10),
    ('Bom Jesus das Selvas', 10),
    ('Bom Lugar', 10),
    ('Brejo', 10),
    ('Brejo de Areia', 10),
    ('Buriti', 10),
    ('Buriti Bravo', 10),
    ('Buriticupu', 10),
    ('Buritirana', 10),
    ('Cachoeira Grande', 10),
    ('Cajapió', 10),
    ('Cajari', 10),
    ('Campestre do Maranhão', 10),
    ('Cândido Mendes', 10),
    ('Cantanhede', 10),
    ('Capinzal do Norte', 10),
    ('Carolina', 10),
    ('Carutapera', 10),
    ('Caxias', 10),
    ('Cedral', 10),
    ('Central do Maranhão', 10),
    ('Centro do Guilherme', 10),
    ('Centro Novo do Maranhão', 10),
    ('Chapadinha', 10),
    ('Cidelândia', 10),
    ('Codó', 10),
    ('Coelho Neto', 10),
    ('Colinas', 10),
    ('Conceição do Lago-Açu', 10),
    ('Coroatá', 10),
    ('Cururupu', 10),
    ('Davinópolis', 10),
    ('Dom Pedro', 10),
    ('Duque Bacelar', 10),
    ('Esperantinópolis', 10),
    ('Estreito', 10),
    ('Feira Nova do Maranhão', 10),
    ('Fernando Falcão', 10),
    ('Formosa da Serra Negra', 10),
    ('Fortaleza dos Nogueiras', 10),
    ('Fortuna', 10),
    ('Godofredo Viana', 10),
    ('Gonçalves Dias', 10),
    ('Governador Archer', 10),
    ('Governador Edison Lobão', 10),
    ('Governador Eugênio Barros', 10),
    ('Governador Luiz Rocha', 10),
    ('Governador Newton Bello', 10),
    ('Governador Nunes Freire', 10),
    ('Graça Aranha', 10),
    ('Grajaú', 10),
    ('Guimarães', 10),
    ('Humberto de Campos', 10),
    ('Icatu', 10),
    ('Igarapé do Meio', 10),
    ('Igarapé Grande', 10),
    ('Imperatriz', 10),
    ('Itaipava do Grajaú', 10),
    ('Itapecuru Mirim', 10),
    ('Itinga do Maranhão', 10),
    ('Jatobá', 10),
    ('Jenipapo dos Vieiras', 10),
    ('João Lisboa', 10),
    ('Joselândia', 10),
    ('Junco do Maranhão', 10),
    ('Lago da Pedra', 10),
    ('Lago do Junco', 10),
    ('Lago dos Rodrigues', 10),
    ('Lago Verde', 10),
    ('Lagoa do Mato', 10),
    ('Lagoa Grande do Maranhão', 10),
    ('Lajeado Novo', 10),
    ('Lima Campos', 10),
    ('Loreto', 10),
    ('Luís Domingues', 10),
    ('Magalhães de Almeida', 10),
    ('Maracaçumé', 10),
    ('Marajá do Sena', 10),
    ('Maranhãozinho', 10),
    ('Mata Roma', 10),
    ('Matinha', 10),
    ('Matões', 10),
    ('Matões do Norte', 10),
    ('Milagres do Maranhão', 10),
    ('Mirador', 10),
    ('Miranda do Norte', 10),
    ('Mirinzal', 10),
    ('Monção', 10),
    ('Montes Altos', 10),
    ('Morros', 10),
    ('Nina Rodrigues', 10),
    ('Nova Colinas', 10),
    ('Nova Iorque', 10),
    ('Nova Olinda do Maranhão', 10),
    ('Olho d`Água das Cunhãs', 10),
    ('Olinda Nova do Maranhão', 10),
    ('Paço do Lumiar', 10),
    ('Palmeirândia', 10),
    ('Paraibano', 10),
    ('Parnarama', 10),
    ('Passagem Franca', 10),
    ('Pastos Bons', 10),
    ('Paulino Neves', 10),
    ('Paulo Ramos', 10),
    ('Pedreiras', 10),
    ('Pedro do Rosário', 10),
    ('Penalva', 10),
    ('Peri Mirim', 10),
    ('Peritoró', 10),
    ('Pindaré-Mirim', 10),
    ('Pinheiro', 10),
    ('Pio XII', 10),
    ('Pirapemas', 10),
    ('Poção de Pedras', 10),
    ('Porto Franco', 10),
    ('Porto Rico do Maranhão', 10),
    ('Presidente Dutra', 10),
    ('Presidente Juscelino', 10),
    ('Presidente Médici', 10),
    ('Presidente Sarney', 10),
    ('Presidente Vargas', 10),
    ('Primeira Cruz', 10),
    ('Raposa', 10),
    ('Riachão', 10),
    ('Ribamar Fiquene', 10),
    ('Rosário', 10),
    ('Sambaíba', 10),
    ('Santa Filomena do Maranhão', 10),
    ('Santa Helena', 10),
    ('Santa Inês', 10),
    ('Santa Luzia', 10),
    ('Santa Luzia do Paruá', 10),
    ('Santa Quitéria do Maranhão', 10),
    ('Santa Rita', 10),
    ('Santana do Maranhão', 10),
    ('Santo Amaro do Maranhão', 10),
    ('Santo Antônio dos Lopes', 10),
    ('São Benedito do Rio Preto', 10),
    ('São Bento', 10),
    ('São Bernardo', 10),
    ('São Domingos do Azeitão', 10),
    ('São Domingos do Maranhão', 10),
    ('São Félix de Balsas', 10),
    ('São Francisco do Brejão', 10),
    ('São Francisco do Maranhão', 10),
    ('São João Batista', 10),
    ('São João do Carú', 10),
    ('São João do Paraíso', 10),
    ('São João do Soter', 10),
    ('São João dos Patos', 10),
    ('São José de Ribamar', 10),
    ('São José dos Basílios', 10),
    ('São Luís', 10),
    ('São Luís Gonzaga do Maranhão', 10),
    ('São Mateus do Maranhão', 10),
    ('São Pedro da Água Branca', 10),
    ('São Pedro dos Crentes', 10),
    ('São Raimundo das Mangabeiras', 10),
    ('São Raimundo do Doca Bezerra', 10),
    ('São Roberto', 10),
    ('São Vicente Ferrer', 10),
    ('Satubinha', 10),
    ('Senador Alexandre Costa', 10),
    ('Senador La Rocque', 10),
    ('Serrano do Maranhão', 10),
    ('Sítio Novo', 10),
    ('Sucupira do Norte', 10),
    ('Sucupira do Riachão', 10),
    ('Tasso Fragoso', 10),
    ('Timbiras', 10),
    ('Timon', 10),
    ('Trizidela do Vale', 10),
    ('Tufilândia', 10),
    ('Tuntum', 10),
    ('Turiaçu', 10),
    ('Turilândia', 10),
    ('Tutóia', 10),
    ('Urbano Santos', 10),
    ('Vargem Grande', 10),
    ('Viana', 10),
    ('Vila Nova dos Martírios', 10),
    ('Vitória do Mearim', 10),
    ('Vitorino Freire', 10),
    ('Zé Doca', 10);