INSERT INTO cidade (nome_cidade, cidade_estado)
VALUES
('Acari', 20),
('Açu', 20),
('Afonso Bezerra', 20),
('Água Nova', 20),
('Alexandria', 20),
('Almino Afonso', 20),
('Alto do Rodrigues', 20),
('Angicos', 20),
('Antônio Martins', 20),
('Apodi', 20),
('Areia Branca', 20),
('Arês', 20),
('Augusto Severo', 20),
('Baía Formosa', 20),
('Baraúna', 20),
('Barcelona', 20),
('Bento Fernandes', 20),
('Bodó', 20),
('Bom Jesus', 20),
('Brejinho', 20),
('Caiçara do Norte', 20),
('Caiçara do Rio do Vento', 20),
('Caicó', 20),
('Campo Redondo', 20),
('Canguaretama', 20),
('Caraúbas', 20),
('Carnaúba dos Dantas', 20),
('Carnaubais', 20),
('Ceará-Mirim', 20),
('Cerro Corá', 20),
('Coronel Ezequiel', 20),
('Coronel João Pessoa', 20),
('Cruzeta', 20),
('Currais Novos', 20),
('Doutor Severiano', 20),
('Encanto', 20),
('Equador', 20),
('Espírito Santo', 20),
('Extremoz', 20),
('Felipe Guerra', 20),
('Fernando Pedroza', 20),
('Florânia', 20),
('Francisco Dantas', 20),
('Frutuoso Gomes', 20),
('Galinhos', 20),
('Goianinha', 20),
('Governador Dix-Sept Rosado', 20),
('Grossos', 20),
('Guamaré', 20),
('Ielmo Marinho', 20),
('Ipanguaçu', 20),
('Ipueira', 20),
('Itajá', 20),
('Itaú', 20),
('Jaçanã', 20),
('Jandaíra', 20),
('Janduís', 20),
('Januário Cicco', 20),
('Japi', 20),
('Jardim de Angicos', 20),
('Jardim de Piranhas', 20),
('Jardim do Seridó', 20),
('João Câmara', 20),
('João Dias', 20),
('José da Penha', 20),
('Jucurutu', 20),
('Jundiá', 20),
('Lagoa d`Anta', 20),
('Lagoa de Pedras', 20),
('Lagoa de Velhos', 20),
('Lagoa Nova', 20),
('Lagoa Salgada', 20),
('Lajes', 20),
('Lajes Pintadas', 20),
('Lucrécia', 20),
('Luís Gomes', 20),
('Macaíba', 20),
('Macau', 20),
('Major Sales', 20),
('Marcelino Vieira', 20),
('Martins', 20),
('Maxaranguape', 20),
('Messias Targino', 20),
('Montanhas', 20),
('Monte Alegre', 20),
('Monte das Gameleiras', 20),
('Mossoró', 20),
('Natal', 20),
('Nísia Floresta', 20),
('Nova Cruz', 20),
('Olho-d`Água do Borges', 20),
('Ouro Branco', 20),
('Paraná', 20),
('Paraú', 20),
('Parazinho', 20),
('Parelhas', 20),
('Parnamirim', 20),
('Passa e Fica', 20),
('Passagem', 20),
('Patu', 20),
('Pau dos Ferros', 20),
('Pedra Grande', 20),
('Pedra Preta', 20),
('Pedro Avelino', 20),
('Pedro Velho', 20),
('Pendências', 20),
('Pilões', 20),
('Poço Branco', 20),
('Portalegre', 20),
('Porto do Mangue', 20),
('Presidente Juscelino', 20),
('Pureza', 20),
('Rafael Fernandes', 20),
('Rafael Godeiro', 20),
('Riacho da Cruz', 20),
('Riacho de Santana', 20),
('Riachuelo', 20),
('Rio do Fogo', 20),
('Rodolfo Fernandes', 20),
('Ruy Barbosa', 20),
('Santa Cruz', 20),
('Santa Maria', 20),
('Santana do Matos', 20),
('Santana do Seridó', 20),
('Santo Antônio', 20),
('São Bento do Norte', 20),
('São Bento do Trairí', 20),
('São Fernando', 20),
('São Francisco do Oeste', 20),
('São Gonçalo do Amarante', 20),
('São João do Sabugi', 20),
('São José de Mipibu', 20),
('São José do Campestre', 20),
('São José do Seridó', 20),
('São Miguel', 20),
('São Miguel do Gostoso', 20),
('São Paulo do Potengi', 20),
('São Pedro', 20),
('São Rafael', 20),
('São Tomé', 20),
('São Vicente', 20),
('Senador Elói de Souza', 20),
('Senador Georgino Avelino', 20),
('Serra Caiada', 20),
('Serra de São Bento', 20),
('Serra do Mel', 20),
('Serra Negra do Norte', 20),
('Serrinha', 20),
('Serrinha dos Pintos', 20),
('Severiano Melo', 20),
('Sítio Novo', 20),
('Taboleiro Grande', 20),
('Taipu', 20),
('Tangará', 20),
('Tenente Ananias', 20),
('Tenente Laurentino Cruz', 20),
('Tibau', 20),
('Tibau do Sul', 20),
('Timbaúba dos Batistas', 20),
('Touros', 20),
('Triunfo Potiguar', 20),
('Umarizal', 20),
('Upanema', 20),
('Várzea', 20),
('Venha-Ver', 20),
('Vera Cruz', 20),
('Viçosa', 20);