INSERT INTO cidade (nome_cidade, cidade_estado) VALUES
('Abaetetuba', 14),
('Abel Figueiredo', 14),
('Acará', 14),
('Afuá', 14),
('Água Azul do Norte', 14),
('Alenquer', 14),
('Almeirim', 14),
('Altamira', 14),
('Anajás', 14),
('Ananindeua', 14),
('Anapu', 14),
('Augusto Corrêa', 14),
('Aurora do Pará', 14),
('Aveiro', 14),
('Bagre', 14),
('Baião', 14),
('Bannach', 14),
('Barcarena', 14),
('Belém', 14),
('Belterra', 14),
('Benevides', 14),
('Bom Jesus do Tocantins', 14),
('Bonito', 14),
('Bragança', 14),
('Brasil Novo', 14),
('Brejo Grande do Araguaia', 14),
('Breu Branco', 14),
('Breves', 14),
('Bujaru', 14),
('Cachoeira do Arari', 14),
('Cachoeira do Piriá', 14),
('Cametá', 14),
('Canaã dos Carajás', 14),
('Capanema', 14),
('Capitão Poço', 14),
('Castanhal', 14),
('Chaves', 14),
('Colares', 14),
('Conceição do Araguaia', 14),
('Concórdia do Pará', 14),
('Cumaru do Norte', 14),
('Curionópolis', 14),
('Curralinho', 14),
('Curuá', 14),
('Curuçá', 14),
('Dom Eliseu', 14),
('Eldorado do Carajás', 14),
('Faro', 14),
('Floresta do Araguaia', 14),
('Garrafão do Norte', 14),
('Goianésia do Pará', 14),
('Gurupá', 14),
('Igarapé-Açu', 14),
('Igarapé-Miri', 14),
('Inhangapi', 14),
('Ipixuna do Pará', 14),
('Irituia', 14),
('Itaituba', 14),
('Itupiranga', 14),
('Jacareacanga', 14),
('Jacundá', 14),
('Juruti', 14),
('Limoeiro do Ajuru', 14),
('Mãe do Rio', 14),
('Magalhães Barata', 14),
('Marabá', 14),
('Maracanã', 14),
('Marapanim', 14),
('Marituba', 14),
('Medicilândia', 14),
('Melgaço', 14),
('Mocajuba', 14),
('Moju', 14),
('Monte Alegre', 14),
('Muaná', 14),
('Nova Esperança do Piriá', 14),
('Nova Ipixuna', 14),
('Nova Timboteua', 14),
('Novo Progresso', 14),
('Novo Repartimento', 14),
('Óbidos', 14),
('Oeiras do Pará', 14),
('Oriximiná', 14),
('Ourém', 14),
('Ourilândia do Norte', 14),
('Pacajá', 14),
('Palestina do Pará', 14),
('Paragominas', 14),
('Parauapebas', 14),
('Pau d''Arco', 14),
('Peixe-Boi', 14),
('Piçarra', 14),
('Placas', 14),
('Ponta de Pedras', 14),
('Portel', 14),
('Porto de Moz', 14),
('Prainha', 14),
('Primavera', 14),
('Quatipuru', 14),
('Redenção', 14),
('Rio Maria', 14),
('Rondon do Pará', 14),
('Rurópolis', 14),
('Salinópolis', 14),
('Salvaterra', 14),
('Santa Bárbara do Pará', 14),
('Santa Cruz do Arari', 14),
('Santa Isabel do Pará', 14),
('Santa Luzia do Pará', 14),
('Santa Maria das Barreiras', 14),
('Santa Maria do Pará', 14),
('Santana do Araguaia', 14),
('Santarém', 14),
('Santarém Novo', 14),
('Santo Antônio do Tauá', 14),
('São Caetano de Odivelas', 14),
('São Domingos do Araguaia', 14),
('São Domingos do Capim', 14),
('São Félix do Xingu', 14),
('São Francisco do Pará', 14),
('São Geraldo do Araguaia', 14),
('São João da Ponta', 14),
('São João de Pirabas', 14),
('São João do Araguaia', 14),
('São Miguel do Guamá', 14),
('São Sebastião da Boa Vista', 14),
('Sapucaia', 14),
('Senador José Porfírio', 14),
('Soure', 14),
('Tailândia', 14),
('Terra Alta', 14),
('Terra Santa', 14),
('Tomé-Açu', 14),
('Tracuateua', 14),
('Trairão', 14),
('Tucumã', 14),
('Tucuruí', 14),
('Ulianópolis', 14),
('Uruará', 14),
('Vigia', 14),
('Viseu', 14),
('Vitória do Xingu', 14),
('Xinguara', 14);
