INSERT INTO cidade (nome_cidade, cidade_estado)
VALUES
    ('Abreu e Lima', 17),
    ('Afogados da Ingazeira', 17),
    ('Afrânio', 17),
    ('Agrestina', 17),
    ('Água Preta', 17),
    ('Águas Belas', 17),
    ('Alagoinha', 17),
    ('Aliança', 17),
    ('Altinho', 17),
    ('Amaraji', 17),
    ('Angelim', 17),
    ('Araçoiaba', 17),
    ('Araripina', 17),
    ('Arcoverde', 17),
    ('Barra de Guabiraba', 17),
    ('Barreiros', 17),
    ('Belém de Maria', 17),
    ('Belém de São Francisco', 17),
    ('Belo Jardim', 17),
    ('Betânia', 17),
    ('Bezerros', 17),
    ('Bodocó', 17),
    ('Bom Conselho', 17),
    ('Bom Jardim', 17),
    ('Bonito', 17),
    ('Brejão', 17),
    ('Brejinho', 17),
    ('Brejo da Madre de Deus', 17),
    ('Buenos Aires', 17),
    ('Buíque', 17),
    ('Cabo de Santo Agostinho', 17),
    ('Cabrobó', 17),
    ('Cachoeirinha', 17),
    ('Caetés', 17),
    ('Caicó', 17),
    ('Calçado', 17),
    ('Calumbi', 17),
    ('Camaragibe', 17),
    ('Camocim de São Félix', 17),
    ('Camutanga', 17),
    ('Canhotinho', 17),
    ('Capoeiras', 17),
    ('Carnaíba', 17),
    ('Carnaubeira da Penha', 17),
    ('Carpina', 17),
    ('Caruaru', 17),
    ('Casinhas', 17),
    ('Catende', 17),
    ('Cedro', 17),
    ('Chã de Alegria', 17),
    ('Chã Grande', 17),
    ('Condado', 17),
    ('Correntes', 17),
    ('Cortês', 17),
    ('Cumaru', 17),
    ('Cupira', 17),
    ('Custódia', 17),
    ('Dormentes', 17),
    ('Escada', 17),
    ('Exu', 17),
    ('Feira Nova', 17),
    ('Fernando de Noronha', 17),
    ('Ferreiros', 17),
    ('Flores', 17),
    ('Floresta', 17),
    ('Frei Miguelinho', 17),
    ('Gameleira', 17),
    ('Garanhuns', 17),
    ('Glória do Goitá', 17),
    ('Goiana', 17),
    ('Granito', 17),
    ('Gravatá', 17),
    ('Iati', 17),
    ('Ibimirim', 17),
    ('Ibirajuba', 17),
    ('Igarassu', 17),
    ('Iguaraci', 17),
    ('Ilha de Itamaracá', 17),
    ('Inajá', 17),
    ('Ingazeira', 17),
    ('Ipojuca', 17),
    ('Ipubi', 17),
    ('Itacuruba', 17),
    ('Itaíba', 17),
    ('Itambé', 17),
    ('Itapetim', 17),
    ('Itapissuma', 17),
    ('Itaquitinga', 17),
    ('Jaboatão dos Guararapes', 17),
    ('Jaqueira', 17),
    ('Jataúba', 17),
    ('Jatobá', 17),
    ('João Alfredo', 17),
    ('Joaquim Nabuco', 17),
    ('Jucati', 17),
    ('Jupi', 17),
    ('Jurema', 17),
    ('Lagoa de Itaenga', 17),
    ('Lagoa do Carro', 17),
    ('Lagoa do Ouro', 17),
    ('Lagoa dos Gatos', 17),
    ('Lagoa Grande', 17),
    ('Lajedo', 17),
    ('Limoeiro', 17),
    ('Macaparana', 17),
    ('Machados', 17),
    ('Manari', 17),
    ('Maraial', 17),
    ('Mirandiba', 17),
    ('Moreno', 17),
    ('Nazaré da Mata', 17),
    ('Olinda', 17),
    ('Orobó', 17),
    ('Orocó', 17),
    ('Ouricuri', 17),
    ('Palmares', 17),
    ('Palmeirina', 17),
    ('Panelas', 17),
    ('Paranatama', 17),
    ('Parnamirim', 17),
    ('Passira', 17),
    ('Paudalho', 17),
    ('Paulista', 17),
    ('Pedra', 17),
    ('Pesqueira', 17),
    ('Petrolândia', 17),
    ('Petrolina', 17),
    ('Poção', 17),
    ('Pombos', 17),
    ('Primavera', 17),
    ('Quipapá', 17),
    ('Quixaba', 17),
    ('Recife', 17),
    ('Riacho das Almas', 17),
    ('Ribeirão', 17),
    ('Rio Formoso', 17),
    ('Sairé', 17),
    ('Salgadinho', 17),
    ('Salgueiro', 17),
    ('Saloá', 17),
    ('Sanharó', 17),
    ('Santa Cruz', 17),
    ('Santa Cruz da Baixa Verde', 17),
    ('Santa Cruz do Capibaribe', 17),
    ('Santa Filomena', 17),
    ('Santa Maria da Boa Vista', 17),
    ('Santa Maria do Cambucá', 17),
    ('Santa Terezinha', 17),
    ('São Benedito do Sul', 17),
    ('São Bento do Una', 17),
    ('São Caitano', 17),
    ('São João', 17),
    ('São Joaquim do Monte', 17),
    ('São José da Coroa Grande', 17),
    ('São José do Belmonte', 17),
    ('São José do Egito', 17),
    ('São Lourenço da Mata', 17),
    ('São Vicente Ferrer', 17),
    ('Serra Talhada', 17),
    ('Serrita', 17),
    ('Sertânia', 17),
    ('Sirinhaém', 17),
    ('Solidão', 17),
    ('Surubim', 17),
    ('Tabira', 17),
    ('Tacaimbó', 17),
    ('Tacaratu', 17),
    ('Tamandaré', 17),
    ('Taquaritinga do Norte', 17),
    ('Terezinha', 17),
    ('Terra Nova', 17),
    ('Timbaúba', 17),
    ('Toritama', 17),
    ('Tracunhaém', 17),
    ('Trindade', 17),
    ('Triunfo', 17),
    ('Tupanatinga', 17),
    ('Tuparetama', 17),
    ('Venturosa', 17),
    ('Verdejante', 17),
    ('Vertente do Lério', 17),
    ('Vertentes', 17),
    ('Vicência', 17),
    ('Vitória de Santo Antão', 17),
    ('Xexéu', 17);
