INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Abaetetuba', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Abel Figueiredo', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Acará', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Afuá', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Água Azul do Norte', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Alenquer', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Almeirim', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Altamira', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Anajás', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Ananindeua', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Anapu', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Augusto Corrêa', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Aurora do Pará', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Aveiro', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Bagre', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Baião', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Bannach', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Barcarena', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Belém', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Belterra', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Benevides', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Bom Jesus do Tocantins', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Bonito', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Bragança', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Brasil Novo', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Brejo Grande do Araguaia', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Breu Branco', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Breves', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Bujaru', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Cachoeira do Arari', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Cachoeira do Piriá', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Cametá', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Canaã dos Carajás', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Capanema', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Capitão Poço', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Castanhal', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Chaves', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Colares', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Conceição do Araguaia', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Concórdia do Pará', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Cumaru do Norte', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Curionópolis', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Curralinho', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Curuá', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Curuçá', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Dom Eliseu', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Eldorado do Carajás', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Faro', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Floresta do Araguaia', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Garrafão do Norte', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Goianésia do Pará', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Gurupá', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Igarapé-Açu', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Igarapé-Miri', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Inhangapi', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Ipixuna do Pará', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Irituia', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Itaituba', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Itupiranga', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Jacareacanga', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Jacundá', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Juruti', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Limoeiro do Ajuru', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Mãe do Rio', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Magalhães Barata', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Marabá', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Maracanã', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Marapanim', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Marituba', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Medicilândia', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Melgaço', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Mocajuba', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Moju', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Monte Alegre', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Muaná', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Nova Esperança do Piriá', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Nova Ipixuna', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Nova Timboteua', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Novo Progresso', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Novo Repartimento', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Óbidos', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Oeiras do Pará', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Oriximiná', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Ourém', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Ourilândia do Norte', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Pacajá', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Palestina do Pará', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Paragominas', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Parauapebas', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Pau d''Arco', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Peixe-Boi', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Piçarra', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Placas', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Ponta de Pedras', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Portel', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Porto de Moz', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Prainha', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Primavera', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Quatipuru', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Redenção', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Rio Maria', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Rondon do Pará', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Rurópolis', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Salinópolis', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Salvaterra', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Santa Bárbara do Pará', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Santa Cruz do Arari', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Santa Isabel do Pará', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Santa Luzia do Pará', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Santa Maria das Barreiras', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Santa Maria do Pará', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Santana do Araguaia', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Santarém', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Santarém Novo', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Santo Antônio do Tauá', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('São Caetano de Odivelas', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('São Domingos do Araguaia', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('São Domingos do Capim', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('São Félix do Xingu', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('São Francisco do Pará', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('São Geraldo do Araguaia', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('São João da Ponta', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('São João de Pirabas', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('São João do Araguaia', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('São Miguel do Guamá', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('São Sebastião da Boa Vista', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Sapucaia', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Senador José Porfírio', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Soure', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Tailândia', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Terra Alta', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Terra Santa', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Tomé-Açu', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Tracuateua', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Trairão', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Tucumã', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Tucuruí', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Ulianópolis', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Uruará', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Vigia', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Viseu', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Vitória do Xingu', 14);
INSERT INTO cidade (nome_cidade, cidade_estado) VALUES ('Xinguara', 14);
