INSERT INTO cidade (nome_cidade, cidade_estado) VALUES
                                                    ('Água Clara', 12),
                                                    ('Alcinópolis', 12),
                                                    ('Amambai', 12),
                                                    ('Anastácio', 12),
                                                    ('Anaurilândia', 12),
                                                    ('Angélica', 12),
                                                    ('Antônio João', 12),
                                                    ('Aparecida do Taboado', 12),
                                                    ('Aquidauana', 12),
                                                    ('Aral Moreira', 12),
                                                    ('Bandeirantes', 12),
                                                    ('Bataguassu', 12),
                                                    ('Bataiporã', 12),
                                                    ('Bela Vista', 12),
                                                    ('Bodoquena', 12),
                                                    ('Bonito', 12),
                                                    ('Brasilândia', 12),
                                                    ('Caarapó', 12),
                                                    ('Camapuã', 12),
                                                    ('Campo Grande', 12),
                                                    ('Caracol', 12),
                                                    ('Cassilândia', 12),
                                                    ('Chapadão do Sul', 12),
                                                    ('Corguinho', 12),
                                                    ('Coronel Sapucaia', 12),
                                                    ('Corumbá', 12),
                                                    ('Costa Rica', 12),
                                                    ('Coxim', 12),
                                                    ('Deodápolis', 12),
                                                    ('Dois Irmãos do Buriti', 12),
                                                    ('Douradina', 12),
                                                    ('Dourados', 12),
                                                    ('Eldorado', 12),
                                                    ('Fátima do Sul', 12),
                                                    ('Figueirão', 12),
                                                    ('Glória de Dourados', 12),
                                                    ('Guia Lopes da Laguna', 12),
                                                    ('Iguatemi', 12),
                                                    ('Inocência', 12),
                                                    ('Itaporã', 12),
                                                    ('Itaquiraí', 12),
                                                    ('Ivinhema', 12),
                                                    ('Japorã', 12),
                                                    ('Jaraguari', 12),
                                                    ('Jardim', 12),
                                                    ('Jateí', 12),
                                                    ('Juti', 12),
                                                    ('Ladário', 12),
                                                    ('Laguna Carapã', 12),
                                                    ('Maracaju', 12),
                                                    ('Miranda', 12),
                                                    ('Mundo Novo', 12),
                                                    ('Naviraí', 12),
                                                    ('Nioaque', 12),
                                                    ('Nova Alvorada do Sul', 12),
                                                    ('Nova Andradina', 12),
                                                    ('Novo Horizonte do Sul', 12),
                                                    ('Paranaíba', 12),
                                                    ('Paranhos', 12),
                                                    ('Pedro Gomes', 12),
                                                    ('Ponta Porã', 12),
                                                    ('Porto Murtinho', 12),
                                                    ('Ribas do Rio Pardo', 12),
                                                    ('Rio Brilhante', 12),
                                                    ('Rio Negro', 12),
                                                    ('Rio Verde de Mato Grosso', 12),
                                                    ('Rochedo', 12),
                                                    ('Santa Rita do Pardo', 12),
                                                    ('São Gabriel do Oeste', 12),
                                                    ('Selvíria', 12),
                                                    ('Sete Quedas', 12),
                                                    ('Sidrolândia', 12),
                                                    ('Sonora', 12),
                                                    ('Tacuru', 12),
                                                    ('Taquarussu', 12),
                                                    ('Terenos', 12),
                                                    ('Três Lagoas', 12),
                                                    ('Vicentina', 12);
