INSERT INTO cidade (nome_cidade, cidade_estado)
VALUES
    ('Adamantina', 25),
    ('Adolfo', 25),
    ('Aguaí', 25),
    ('Águas da Prata', 25),
    ('Águas de Lindóia', 25),
    ('Águas de Santa Bárbara', 25),
    ('Águas de São Pedro', 25),
    ('Agudos', 25),
    ('Alambari', 25),
    ('Alfredo Marcondes', 25),
    ('Altair', 25),
    ('Altinópolis', 25),
    ('Alto Alegre', 25),
    ('Alumínio', 25),
    ('Álvares Florence', 25),
    ('Álvares Machado', 25),
    ('Álvaro de Carvalho', 25),
    ('Alvinlândia', 25),
    ('Americana', 25),
    ('Américo Brasiliense', 25),
    ('Américo de Campos', 25),
    ('Amparo', 25),
    ('Analândia', 25),
    ('Andradina', 25),
    ('Angatuba', 25),
    ('Anhembi', 25),
    ('Anhumas', 25),
    ('Aparecida', 25),
    ('Aparecida d Oeste', 25),
('Apiaí', 25),
('Araçariguama', 25),
('Araçatuba', 25),
('Araçoiaba da Serra', 25),
('Aramina', 25),
('Arandu', 25),
('Arapeí', 25),
('Araraquara', 25),
('Araras', 25),
('Arco-Íris', 25),
('Arealva', 25),
('Areias', 25),
('Areiópolis', 25),
('Ariranha', 25),
('Artur Nogueira', 25),
('Arujá', 25),
('Aspásia', 25),
('Assis', 25),
('Atibaia', 25),
('Auriflama', 25),
('Avaí', 25),
('Avanhandava', 25),
('Avaré', 25),
('Bady Bassitt', 25),
('Balbinos', 25),
('Bálsamo', 25),
('Bananal', 25),
('Barão de Antonina', 25),
('Barbosa', 25),
('Bariri', 25),
('Barra Bonita', 25),
('Barra do Chapéu', 25),
('Barra do Turvo', 25),
('Barretos', 25),
('Barrinha', 25),
('Barueri', 25),
('Bastos', 25),
('Batatais', 25),
('Bauru', 25),
('Bebedouro', 25),
('Bento de Abreu', 25),
('Bernardino de Campos', 25),
('Bertioga', 25),
('Bilac', 25),
('Birigui', 25),
('Biritiba-Mirim', 25),
('Boa Esperança do Sul', 25),
('Bocaina', 25),
('Bofete', 25),
('Boituva', 25),
('Bom Jesus dos Perdões', 25),
('Bom Sucesso de Itararé', 25),
('Borá', 25),
('Boracéia', 25),
('Borborema', 25),
('Borebi', 25),
('Botucatu', 25),
('Bragança Paulista', 25),
('Braúna', 25),
('Brejo Alegre', 25),
('Brodowski', 25),
('Brotas', 25),
('Buri', 25),
('Buritama', 25),
('Buritizal', 25),
('Cabrália Paulista', 25),
('Cabreúva', 25),
('Caçapava', 25),
('Cachoeira Paulista', 25),
('Caconde', 25),
('Cafelândia', 25),
('Caiabu', 25),
('Caieiras', 25),
('Caiuá', 25),
('Cajamar', 25),
('Cajati', 25),
('Cajobi', 25),
('Cajuru', 25),
('Campina do Monte Alegre', 25),
('Campinas', 25),
('Campo Limpo Paulista', 25),
('Campos do Jordão', 25),
('Campos Novos Paulista', 25),
('Cananéia', 25),
('Canas', 25),
('Cândido Motta', 25),
('Cândido Rodrigues', 25),
('Canitar', 25),
('Capão Bonito', 25),
('Capela do Alto', 25),
('Capivari', 25),
('Caraguatatuba', 25),
('Carapicuíba', 25),
('Cardoso', 25),
('Casa Branca', 25),
('Cássia dos Coqueiros', 25),
('Castilho', 25),
('Catanduva', 25),
('Catiguá', 25),
('Cedral', 25),
('Cerqueira César', 25),
('Cerquilho', 25),
('Cesário Lange', 25),
('Charqueada', 25),
('Chavantes', 25),
('Clementina', 25),
('Colina', 25),
('Colômbia', 25),
('Conchal', 25),
('Conchas', 25),
('Cordeirópolis', 25),
('Coroados', 25),
('Coronel Macedo', 25),
('Corumbataí', 25),
('Cosmópolis', 25),
('Cosmorama', 25),
('Cotia', 25),
('Cravinhos', 25),
('Cristais Paulista', 25),
('Cruzália', 25),
('Cruzeiro', 25),
('Cubatão', 25),
('Cunha', 25),
('Descalvado', 25),
('Diadema', 25),
('Dirce Reis', 25),
('Divinolândia', 25),
('Dobrada', 25),
('Dois Córregos', 25),
('Dolcinópolis', 25),
('Dourado', 25),
('Dracena', 25),
('Duartina', 25),
('Dumont', 25),
('Echaporã', 25),
('Eldorado', 25),
('Elias Fausto', 25),
('Elisiário', 25),
('Embaúba', 25),
('Embu', 25),
('Embu-Guaçu', 25),
('Emilianópolis', 25),
('Engenheiro Coelho', 25),
('Espírito Santo do Pinhal', 25),
('Espírito Santo do Turvo', 25),
('Estiva Gerbi', 25),
('Estrela d Oeste', 25),
    ('Estrela do Norte', 25),
    ('Euclides da Cunha Paulista', 25),
    ('Fartura', 25),
    ('Fernando Prestes', 25),
    ('Fernandópolis', 25),
    ('Fernão', 25),
    ('Ferraz de Vasconcelos', 25),
    ('Flora Rica', 25),
    ('Floreal', 25),
    ('Flórida Paulista', 25),
    ('Florínia', 25),
    ('Franca', 25),
    ('Francisco Morato', 25),
    ('Franco da Rocha', 25),
    ('Gabriel Monteiro', 25),
    ('Gália', 25),
    ('Garça', 25),
    ('Gastão Vidigal', 25),
    ('Gavião Peixoto', 25),
    ('General Salgado', 25),
    ('Getulina', 25),
    ('Glicério', 25),
    ('Guaiçara', 25),
    ('Guaimbê', 25),
    ('Guaíra', 25),
    ('Guapiaçu', 25),
    ('Guapiara', 25),
    ('Guará', 25),
    ('Guaraçaí', 25),
    ('Guaraci', 25),
    ('Guarani Oeste', 25),
('Guarantã', 25),
('Guararapes', 25),
('Guararema', 25),
('Guaratinguetá', 25),
('Guareí', 25),
('Guariba', 25),
('Guarujá', 25),
('Guarulhos', 25),
('Guatapará', 25),
('Guzolândia', 25),
('Herculândia', 25),
('Holambra', 25),
('Hortolândia', 25),
('Iacanga', 25),
('Iacri', 25),
('Iaras', 25),
('Ibaté', 25),
('Ibirá', 25),
('Ibirarema', 25),
('Ibitinga', 25),
('Ibiúna', 25),
('Icém', 25),
('Iepê', 25),
('Igaraçu do Tietê', 25),
('Igarapava', 25),
('Igaratá', 25),
('Iguape', 25),
('Ilhabela', 25),
('Ilha Comprida', 25),
('Ilha Solteira', 25),
('Indaiatuba', 25),
('Indiana', 25),
('Indiaporã', 25),
('Inúbia Paulista', 25),
('Ipauçu', 25),
('Iperó', 25),
('Ipeúna', 25),
('Ipiguá', 25),
('Iporanga', 25),
('Ipuã', 25),
('Iracemápolis', 25),
('Irapuã', 25),
('Irapuru', 25),
('Itaberá', 25),
('Itaí', 25),
('Itajobi', 25),
('Itaju', 25),
('Itanhaém', 25),
('Itaóca', 25),
('Itapecerica da Serra', 25),
('Itapetininga', 25),
('Itapeva', 25),
('Itapevi', 25),
('Itapira', 25),
('Itapirapuã Paulista', 25),
('Itápolis', 25),
('Itaporanga', 25),
('Itapuí', 25),
('Itapura', 25),
('Itaquaquecetuba', 25),
('Itararé', 25),
('Itariri', 25),
('Itatiba', 25),
('Itatinga', 25),
('Itirapina', 25),
('Itirapuã', 25),
('Itobi', 25),
('Itu', 25),
('Itupeva', 25),
('Ituverava', 25),
('Jaborandi', 25),
('Jaboticabal', 25),
('Jacareí', 25),
('Jaci', 25),
('Jacupiranga', 25),
('Jaguariúna', 25),
('Jales', 25),
('Jambeiro', 25),
('Jandira', 25),
('Jardinópolis', 25),
('Jarinu', 25),
('Jaú', 25),
('Jeriquara', 25),
('Joanópolis', 25),
('João Ramalho', 25),
('José Bonifácio', 25),
('Júlio Mesquita', 25),
('Jumirim', 25),
('Jundiaí', 25),
('Junqueirópolis', 25),
('Juquiá', 25),
('Juquitiba', 25),
('Lagoinha', 25),
('Laranjal Paulista', 25),
('Lavínia', 25),
('Lavrinhas', 25),
('Leme', 25),
('Lençóis Paulista', 25),
('Limeira', 25),
('Lindóia', 25),
('Lins', 25),
('Lorena', 25),
('Lourdes', 25),
('Louveira', 25),
('Lucélia', 25),
('Lucianópolis', 25),
('Luís Antônio', 25),
('Luiziânia', 25),
('Lupércio', 25),
('Lutécia', 25),
('Macatuba', 25),
('Macaubal', 25),
('Macedônia', 25),
('Magda', 25),
('Mairinque', 25),
('Mairiporã', 25),
('Manduri', 25),
('Marabá Paulista', 25),
('Maracaí', 25),
('Marapoama', 25),
('Mariápolis', 25),
('Marília', 25),
('Marinópolis', 25),
('Martinópolis', 25),
('Matão', 25),
('Mauá', 25),
('Mendonça', 25),
('Meridiano', 25),
('Mesópolis', 25),
('Miguelópolis', 25),
('Mineiros do Tietê', 25),
('Mira Estrela', 25),
('Miracatu', 25),
('Mirandópolis', 25),
('Mirante do Paranapanema', 25),
('Mirassol', 25),
('Mirassolândia', 25),
('Mococa', 25),
('Mogi das Cruzes', 25),
('Mogi Guaçu', 25),
('Mogi Mirim', 25),
('Mombuca', 25),
('Monções', 25),
('Mongaguá', 25),
('Monte Alegre do Sul', 25),
('Monte Alto', 25),
('Monte Aprazível', 25),
('Monte Azul Paulista', 25),
('Monte Castelo', 25),
('Monte Mor', 25),
('Monteiro Lobato', 25),
('Morro Agudo', 25),
('Morungaba', 25),
('Motuca', 25),
('Murutinga do Sul', 25),
('Nantes', 25),
('Narandiba', 25),
('Natividade da Serra', 25),
('Nazaré Paulista', 25),
('Neves Paulista', 25),
('Nhandeara', 25),
('Nipoã', 25),
('Nova Aliança', 25),
('Nova Campina', 25),
('Nova Canaã Paulista', 25),
('Nova Castilho', 25),
('Nova Europa', 25),
('Nova Granada', 25),
('Nova Guataporanga', 25),
('Nova Independência', 25),
('Nova Luzitânia', 25),
('Nova Odessa', 25),
('Novais', 25),
('Novo Horizonte', 25),
('Nuporanga', 25),
('Ocauçu', 25),
('Óleo', 25),
('Olímpia', 25),
('Onda Verde', 25),
('Oriente', 25),
('Orindiúva', 25),
('Orlândia', 25),
('Osasco', 25),
('Oscar Bressane', 25),
('Osvaldo Cruz', 25),
('Ourinhos', 25),
('Ouro Verde', 25),
('Ouroeste', 25),
('Pacaembu', 25),
('Palestina', 25),
('Palmares Paulista', 25),
('Palmeira do Oeste', 25),
    ('Palmital', 25),
    ('Panorama', 25),
    ('Paraguaçu Paulista', 25),
    ('Paraibuna', 25),
    ('Paraíso', 25),
    ('Paranapanema', 25),
    ('Paranapuã', 25),
    ('Parapuã', 25),
    ('Pardinho', 25),
    ('Pariquera-Açu', 25),
    ('Parisi', 25),
    ('Patrocínio Paulista', 25),
    ('Paulicéia', 25),
    ('Paulínia', 25),
    ('Paulistânia', 25),
    ('Paulo de Faria', 25),
    ('Pederneiras', 25),
    ('Pedra Bela', 25),
    ('Pedranópolis', 25),
    ('Pedregulho', 25),
    ('Pedreira', 25),
    ('Pedrinhas Paulista', 25),
    ('Pedro de Toledo', 25),
    ('Penápolis', 25),
    ('Pereira Barreto', 25),
    ('Pereiras', 25),
    ('Peruíbe', 25),
    ('Piacatu', 25),
    ('Piedade', 25),
    ('Pilar do Sul', 25),
    ('Pindamonhangaba', 25),
    ('Pindorama', 25),
    ('Pinhalzinho', 25),
    ('Piquerobi', 25),
    ('Piquete', 25),
    ('Piracaia', 25),
    ('Piracicaba', 25),
    ('Piraju', 25),
    ('Pirajuí', 25),
    ('Pirangi', 25),
    ('Pirapora do Bom Jesus', 25),
    ('Pirapozinho', 25),
    ('Pirassununga', 25),
    ('Piratininga', 25),
    ('Pitangueiras', 25),
    ('Planalto', 25),
    ('Platina', 25),
    ('Poá', 25),
    ('Poloni', 25),
    ('Pompéia', 25),
    ('Pongaí', 25),
    ('Pontal', 25),
    ('Pontalinda', 25),
    ('Pontes Gestal', 25),
    ('Populina', 25),
    ('Porangaba', 25),
    ('Porto Feliz', 25),
    ('Porto Ferreira', 25),
    ('Potim', 25),
    ('Potirendaba', 25),
    ('Pracinha', 25),
    ('Pradópolis', 25),
    ('Praia Grande', 25),
    ('Pratânia', 25),
    ('Presidente Alves', 25),
    ('Presidente Bernardes', 25),
    ('Presidente Epitácio', 25),
    ('Presidente Prudente', 25),
    ('Presidente Venceslau', 25),
    ('Promissão', 25),
    ('Quadra', 25),
    ('Quatá', 25),
    ('Queiroz', 25),
    ('Queluz', 25),
    ('Quintana', 25),
    ('Rafard', 25),
    ('Rancharia', 25),
    ('Redenção da Serra', 25),
    ('Regente Feijó', 25),
    ('Reginópolis', 25),
    ('Registro', 25),
    ('Restinga', 25),
    ('Ribeira', 25),
    ('Ribeirão Bonito', 25),
    ('Ribeirão Branco', 25),
    ('Ribeirão Corrente', 25),
    ('Ribeirão do Sul', 25),
    ('Ribeirão dos Índios', 25),
    ('Ribeirão Grande', 25),
    ('Ribeirão Pires', 25),
    ('Ribeirão Preto', 25),
    ('Riversul', 25),
    ('Rifaina', 25),
    ('Rincão', 25),
    ('Rinópolis', 25),
    ('Rio Claro', 25),
    ('Rio das Pedras', 25),
    ('Rio Grande da Serra', 25),
    ('Riolândia', 25),
    ('Riversul', 25),
    ('Rosana', 25),
    ('Roseira', 25),
    ('Rubiácea', 25),
    ('Rubinéia', 25),
    ('Sabino', 25),
    ('Sagres', 25),
    ('Sales', 25),
    ('Sales Oliveira', 25),
    ('Salesópolis', 25),
    ('Salmourão', 25),
    ('Saltinho', 25),
    ('Salto', 25),
    ('Salto de Pirapora', 25),
    ('Salto Grande', 25),
    ('Sandovalina', 25),
    ('Santa Adélia', 25),
    ('Santa Albertina', 25),
    ('Santa Bárbara do Oeste', 25),
('Santa Branca', 25),
('Santa Clara do Oeste', 25),
    ('Santa Cruz da Conceição', 25),
    ('Santa Cruz da Esperança', 25),
    ('Santa Cruz das Palmeiras', 25),
    ('Santa Cruz do Rio Pardo', 25),
    ('Santa Ernestina', 25),
    ('Santa Fé do Sul', 25),
    ('Santa Gertrudes', 25),
    ('Santa Isabel', 25),
    ('Santa Lúcia', 25),
    ('Santa Maria da Serra', 25),
    ('Santa Mercedes', 25),
    ('Santa Rita do Oeste', 25),
('Santa Rita do Passa Quatro', 25),
('Santa Rosa de Viterbo', 25),
('Santa Salete', 25),
('Santana da Ponte Pensa', 25),
('Santana de Parnaíba', 25),
('Santo Anastácio', 25),
('Santo André', 25),
('Santo Antônio da Alegria', 25),
('Santo Antônio de Posse', 25),
('Santo Antônio do Aracanguá', 25),
('Santo Antônio do Jardim', 25),
('Santo Antônio do Pinhal', 25),
('Santo Expedito', 25),
('Santópolis do Aguapeí', 25),
('Santos', 25),
('São Bento do Sapucaí', 25),
('São Bernardo do Campo', 25),
('São Caetano do Sul', 25),
('São Carlos', 25),
('São Francisco', 25),
('São João da Boa Vista', 25),
('São João das Duas Pontes', 25),
('São João de Iracema', 25),
('São João do Pau do Alho', 25),
    ('São Joaquim da Barra', 25),
    ('São José da Bela Vista', 25),
    ('São José do Barreiro', 25),
    ('São José do Rio Pardo', 25),
    ('São José do Rio Preto', 25),
    ('São José dos Campos', 25),
    ('São Lourenço da Serra', 25),
    ('São Luís do Paraitinga', 25),
    ('São Manuel', 25),
    ('São Miguel Arcanjo', 25),
    ('São Paulo', 25),
    ('São Pedro', 25),
    ('São Pedro do Turvo', 25),
    ('São Roque', 25),
    ('São Sebastião', 25),
    ('São Sebastião da Grama', 25),
    ('São Simão', 25),
    ('São Vicente', 25),
    ('Sarapuí', 25),
    ('Sarutaiá', 25),
    ('Sebastianópolis do Sul', 25),
    ('Serra Azul', 25),
    ('Serra Negra', 25),
    ('Serrana', 25),
    ('Sertãozinho', 25),
    ('Sete Barras', 25),
    ('Severínia', 25),
    ('Silveiras', 25),
    ('Socorro', 25),
    ('Sorocaba', 25),
    ('Sud Mennucci', 25),
    ('Sumaré', 25),
    ('Suzanápolis', 25),
    ('Suzano', 25),
    ('Tabapuã', 25),
    ('Tabatinga', 25),
    ('Taboão da Serra', 25),
    ('Taciba', 25),
    ('Taguaí', 25),
    ('Taiaçu', 25),
    ('Taiúva', 25),
    ('Tambaú', 25),
    ('Tanabi', 25),
    ('Tapiraí', 25),
    ('Tapiratiba', 25),
    ('Taquaral', 25),
    ('Taquaritinga', 25),
    ('Taquarituba', 25),
    ('Taquarivaí', 25),
    ('Tarabai', 25),
    ('Tarumã', 25),
    ('Tatuí', 25),
    ('Taubaté', 25),
    ('Tejupá', 25),
    ('Teodoro Sampaio', 25),
    ('Terra Roxa', 25),
    ('Tietê', 25),
    ('Timburi', 25),
    ('Torre de Pedra', 25),
    ('Torrinha', 25),
    ('Trabiju', 25),
    ('Tremembé', 25),
    ('Três Fronteiras', 25),
    ('Tuiuti', 25),
    ('Tupã', 25),
    ('Tupi Paulista', 25),
    ('Turiúba', 25),
    ('Turmalina', 25),
    ('Ubarana', 25),
    ('Ubatuba', 25),
    ('Ubirajara', 25),
    ('Uchoa', 25),
    ('União Paulista', 25),
    ('Urânia', 25),
    ('Uru', 25),
    ('Urupês', 25),
    ('Valentim Gentil', 25),
    ('Valinhos', 25),
    ('Valparaíso', 25),
    ('Vargem', 25),
    ('Vargem Grande do Sul', 25),
    ('Vargem Grande Paulista', 25),
    ('Várzea Paulista', 25),
    ('Vera Cruz', 25),
    ('Vinhedo', 25),
    ('Viradouro', 25),
    ('Vista Alegre do Alto', 25),
    ('Vitória Brasil', 25),
    ('Votorantim', 25),
    ('Votuporanga', 25),
    ('Zacarias', 25);