INSERT INTO bairro (nome_bairro, bairro_cidade) VALUES
                                                    ('Boa Vista', 76),
                                                    ('Centro', 76),
                                                    ('Comerciário', 76),
                                                    ('Metropol', 76),
                                                    ('Michel', 76),
                                                    ('Nossa Senhora da Salete', 76),
                                                    ('Pinheirinho', 76),
                                                    ('Pio Corrêa', 76),
                                                    ('Próspera', 76),
                                                    ('Quarta Linha', 76),
                                                    ('Renascer', 76),
                                                    ('Rio Maina', 76),
                                                    ('Santa Augusta', 76),
                                                    ('Santa Bárbara', 76),
                                                    ('Santa Luzia', 76),
                                                    ('Santo Antônio', 76),
                                                    ('São Luiz', 76),
                                                    ('São Simão', 76),
                                                    ('Vila Rica', 76),
                                                    ('Vila Zuleima', 76);
